// Code generated by ent, DO NOT EDIT.

package pattern

import (
	"defly-defender/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Pattern {
	return predicate.Pattern(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldName, v))
}

// Phase applies equality check predicate on the "phase" field. It's identical to PhaseEQ.
func Phase(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldPhase, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Pattern {
	return predicate.Pattern(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Pattern {
	return predicate.Pattern(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Pattern {
	return predicate.Pattern(sql.FieldContainsFold(FieldName, v))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...int) predicate.Pattern {
	return predicate.Pattern(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...int) predicate.Pattern {
	return predicate.Pattern(sql.FieldNotIn(FieldPhase, vs...))
}

// PhaseGT applies the GT predicate on the "phase" field.
func PhaseGT(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldGT(FieldPhase, v))
}

// PhaseGTE applies the GTE predicate on the "phase" field.
func PhaseGTE(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldGTE(FieldPhase, v))
}

// PhaseLT applies the LT predicate on the "phase" field.
func PhaseLT(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldLT(FieldPhase, v))
}

// PhaseLTE applies the LTE predicate on the "phase" field.
func PhaseLTE(v int) predicate.Pattern {
	return predicate.Pattern(sql.FieldLTE(FieldPhase, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Pattern {
	return predicate.Pattern(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Pattern {
	return predicate.Pattern(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Pattern {
	return predicate.Pattern(sql.FieldNotIn(FieldType, vs...))
}

// DatatypeEQ applies the EQ predicate on the "datatype" field.
func DatatypeEQ(v Datatype) predicate.Pattern {
	return predicate.Pattern(sql.FieldEQ(FieldDatatype, v))
}

// DatatypeNEQ applies the NEQ predicate on the "datatype" field.
func DatatypeNEQ(v Datatype) predicate.Pattern {
	return predicate.Pattern(sql.FieldNEQ(FieldDatatype, v))
}

// DatatypeIn applies the In predicate on the "datatype" field.
func DatatypeIn(vs ...Datatype) predicate.Pattern {
	return predicate.Pattern(sql.FieldIn(FieldDatatype, vs...))
}

// DatatypeNotIn applies the NotIn predicate on the "datatype" field.
func DatatypeNotIn(vs ...Datatype) predicate.Pattern {
	return predicate.Pattern(sql.FieldNotIn(FieldDatatype, vs...))
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.Pattern {
	return predicate.Pattern(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TargetsTable, TargetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.Target) predicate.Pattern {
	return predicate.Pattern(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pattern) predicate.Pattern {
	return predicate.Pattern(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pattern) predicate.Pattern {
	return predicate.Pattern(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pattern) predicate.Pattern {
	return predicate.Pattern(sql.NotPredicates(p))
}
