// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActionsColumns holds the columns for the "actions" table.
	ActionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"allow", "deny", "log", "request", "report", "suspect", "setter", "score", "level"}},
		{Name: "configurations", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
	}
	// ActionsTable holds the schema information for the "actions" table.
	ActionsTable = &schema.Table{
		Name:       "actions",
		Columns:    ActionsColumns,
		PrimaryKey: []*schema.Column{ActionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "actions_users_created_actions",
				Columns:    []*schema.Column{ActionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DecisionsColumns holds the columns for the "decisions" table.
	DecisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "direction", Type: field.TypeEnum, Enums: []string{"request", "response"}},
		{Name: "condition", Type: field.TypeEnum, Enums: []string{"<=", "<", "=", ">=", ">"}},
		{Name: "score", Type: field.TypeFloat64},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"allow", "deny", "rewrite_headers", "rewrite_body", "redirect", "cancel", "rewrite", "save", "erase_cookies", "force_no_cache"}},
		{Name: "configurations", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
	}
	// DecisionsTable holds the schema information for the "decisions" table.
	DecisionsTable = &schema.Table{
		Name:       "decisions",
		Columns:    DecisionsColumns,
		PrimaryKey: []*schema.Column{DecisionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "decisions_users_created_decisions",
				Columns:    []*schema.Column{DecisionsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EnginesColumns holds the columns for the "engines" table.
	EnginesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "input_datatype", Type: field.TypeEnum, Enums: []string{"array", "number", "string"}},
		{Name: "type", Type: field.TypeString},
		{Name: "configurations", Type: field.TypeJSON, Nullable: true},
		{Name: "output_datatype", Type: field.TypeEnum, Enums: []string{"array", "number", "string"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
	}
	// EnginesTable holds the schema information for the "engines" table.
	EnginesTable = &schema.Table{
		Name:       "engines",
		Columns:    EnginesColumns,
		PrimaryKey: []*schema.Column{EnginesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "engines_users_created_engines",
				Columns:    []*schema.Column{EnginesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// PatternsColumns holds the columns for the "patterns" table.
	PatternsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "phase", Type: field.TypeInt},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"full", "header", "meta", "query", "body", "file"}},
		{Name: "datatype", Type: field.TypeEnum, Enums: []string{"array", "number", "string"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PatternsTable holds the schema information for the "patterns" table.
	PatternsTable = &schema.Table{
		Name:       "patterns",
		Columns:    PatternsColumns,
		PrimaryKey: []*schema.Column{PatternsColumns[0]},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "applied_for", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// PrinciplesColumns holds the columns for the "principles" table.
	PrinciplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "level", Type: field.TypeUint64, Default: 1},
		{Name: "phase", Type: field.TypeInt},
		{Name: "validation_status", Type: field.TypeEnum, Nullable: true, Enums: []string{"pending", "validating", "failed", "passed"}},
		{Name: "validation_details", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
	}
	// PrinciplesTable holds the schema information for the "principles" table.
	PrinciplesTable = &schema.Table{
		Name:       "principles",
		Columns:    PrinciplesColumns,
		PrimaryKey: []*schema.Column{PrinciplesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "principles_users_created_principles",
				Columns:    []*schema.Column{PrinciplesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "phase", Type: field.TypeInt},
		{Name: "comparator", Type: field.TypeString},
		{Name: "is_inversed", Type: field.TypeBool, Default: false},
		{Name: "configurations", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "target_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "wordlist_id", Type: field.TypeUUID, Nullable: true},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_targets_rules",
				Columns:    []*schema.Column{RulesColumns[10]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "rules_users_created_rules",
				Columns:    []*schema.Column{RulesColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "rules_wordlists_rules",
				Columns:    []*schema.Column{RulesColumns[12]},
				RefColumns: []*schema.Column{WordlistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "phase", Type: field.TypeInt},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"getter", "full", "header", "meta", "query", "body", "file"}},
		{Name: "datatype", Type: field.TypeEnum, Enums: []string{"array", "number", "string"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "pattern_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "wordlist_id", Type: field.TypeUUID, Nullable: true},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "targets_patterns_targets",
				Columns:    []*schema.Column{TargetsColumns[9]},
				RefColumns: []*schema.Column{PatternsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "targets_users_created_targets",
				Columns:    []*schema.Column{TargetsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "targets_wordlists_targets",
				Columns:    []*schema.Column{TargetsColumns[11]},
				RefColumns: []*schema.Column{WordlistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "is_verified", Type: field.TypeBool, Default: false},
		{Name: "is_activated", Type: field.TypeBool, Default: true},
		{Name: "is_root", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WordlistsColumns holds the columns for the "wordlists" table.
	WordlistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"file", "json"}},
		{Name: "word_file", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "word_json", Type: field.TypeJSON, Nullable: true},
		{Name: "word_count", Type: field.TypeInt, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
	}
	// WordlistsTable holds the schema information for the "wordlists" table.
	WordlistsTable = &schema.Table{
		Name:       "wordlists",
		Columns:    WordlistsColumns,
		PrimaryKey: []*schema.Column{WordlistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wordlists_users_created_wordlists",
				Columns:    []*schema.Column{WordlistsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RulesActionsColumns holds the columns for the "rules_actions" table.
	RulesActionsColumns = []*schema.Column{
		{Name: "action", Type: field.TypeUUID},
		{Name: "rule", Type: field.TypeUUID},
	}
	// RulesActionsTable holds the schema information for the "rules_actions" table.
	RulesActionsTable = &schema.Table{
		Name:       "rules_actions",
		Columns:    RulesActionsColumns,
		PrimaryKey: []*schema.Column{RulesActionsColumns[0], RulesActionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_actions_action",
				Columns:    []*schema.Column{RulesActionsColumns[0]},
				RefColumns: []*schema.Column{ActionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "rules_actions_rule",
				Columns:    []*schema.Column{RulesActionsColumns[1]},
				RefColumns: []*schema.Column{RulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TargetsEnginesColumns holds the columns for the "targets_engines" table.
	TargetsEnginesColumns = []*schema.Column{
		{Name: "engine", Type: field.TypeUUID},
		{Name: "target", Type: field.TypeUUID},
	}
	// TargetsEnginesTable holds the schema information for the "targets_engines" table.
	TargetsEnginesTable = &schema.Table{
		Name:       "targets_engines",
		Columns:    TargetsEnginesColumns,
		PrimaryKey: []*schema.Column{TargetsEnginesColumns[0], TargetsEnginesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "targets_engines_engine",
				Columns:    []*schema.Column{TargetsEnginesColumns[0]},
				RefColumns: []*schema.Column{EnginesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "targets_engines_target",
				Columns:    []*schema.Column{TargetsEnginesColumns[1]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// GroupPermissionsColumns holds the columns for the "group_permissions" table.
	GroupPermissionsColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeUUID},
		{Name: "permission_id", Type: field.TypeUUID},
	}
	// GroupPermissionsTable holds the schema information for the "group_permissions" table.
	GroupPermissionsTable = &schema.Table{
		Name:       "group_permissions",
		Columns:    GroupPermissionsColumns,
		PrimaryKey: []*schema.Column{GroupPermissionsColumns[0], GroupPermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_permissions_group_id",
				Columns:    []*schema.Column{GroupPermissionsColumns[0]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_permissions_permission_id",
				Columns:    []*schema.Column{GroupPermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PrinciplesRulesColumns holds the columns for the "principles_rules" table.
	PrinciplesRulesColumns = []*schema.Column{
		{Name: "rule", Type: field.TypeUUID},
		{Name: "principle", Type: field.TypeUUID},
	}
	// PrinciplesRulesTable holds the schema information for the "principles_rules" table.
	PrinciplesRulesTable = &schema.Table{
		Name:       "principles_rules",
		Columns:    PrinciplesRulesColumns,
		PrimaryKey: []*schema.Column{PrinciplesRulesColumns[0], PrinciplesRulesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "principles_rules_rule",
				Columns:    []*schema.Column{PrinciplesRulesColumns[0]},
				RefColumns: []*schema.Column{RulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "principles_rules_principle",
				Columns:    []*schema.Column{PrinciplesRulesColumns[1]},
				RefColumns: []*schema.Column{PrinciplesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserGroupsColumns holds the columns for the "user_groups" table.
	UserGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "group_id", Type: field.TypeUUID},
	}
	// UserGroupsTable holds the schema information for the "user_groups" table.
	UserGroupsTable = &schema.Table{
		Name:       "user_groups",
		Columns:    UserGroupsColumns,
		PrimaryKey: []*schema.Column{UserGroupsColumns[0], UserGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_groups_user_id",
				Columns:    []*schema.Column{UserGroupsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_groups_group_id",
				Columns:    []*schema.Column{UserGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserPermissionsColumns holds the columns for the "user_permissions" table.
	UserPermissionsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "permission_id", Type: field.TypeUUID},
	}
	// UserPermissionsTable holds the schema information for the "user_permissions" table.
	UserPermissionsTable = &schema.Table{
		Name:       "user_permissions",
		Columns:    UserPermissionsColumns,
		PrimaryKey: []*schema.Column{UserPermissionsColumns[0], UserPermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_permissions_user_id",
				Columns:    []*schema.Column{UserPermissionsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_permissions_permission_id",
				Columns:    []*schema.Column{UserPermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActionsTable,
		DecisionsTable,
		EnginesTable,
		GroupsTable,
		PatternsTable,
		PermissionsTable,
		PrinciplesTable,
		RulesTable,
		TargetsTable,
		UsersTable,
		WordlistsTable,
		RulesActionsTable,
		TargetsEnginesTable,
		GroupPermissionsTable,
		PrinciplesRulesTable,
		UserGroupsTable,
		UserPermissionsTable,
	}
)

func init() {
	ActionsTable.ForeignKeys[0].RefTable = UsersTable
	DecisionsTable.ForeignKeys[0].RefTable = UsersTable
	EnginesTable.ForeignKeys[0].RefTable = UsersTable
	PrinciplesTable.ForeignKeys[0].RefTable = UsersTable
	PrinciplesTable.Annotation = &entsql.Annotation{
		Table: "principles",
	}
	RulesTable.ForeignKeys[0].RefTable = TargetsTable
	RulesTable.ForeignKeys[1].RefTable = UsersTable
	RulesTable.ForeignKeys[2].RefTable = WordlistsTable
	TargetsTable.ForeignKeys[0].RefTable = PatternsTable
	TargetsTable.ForeignKeys[1].RefTable = UsersTable
	TargetsTable.ForeignKeys[2].RefTable = WordlistsTable
	WordlistsTable.ForeignKeys[0].RefTable = UsersTable
	RulesActionsTable.ForeignKeys[0].RefTable = ActionsTable
	RulesActionsTable.ForeignKeys[1].RefTable = RulesTable
	TargetsEnginesTable.ForeignKeys[0].RefTable = EnginesTable
	TargetsEnginesTable.ForeignKeys[1].RefTable = TargetsTable
	GroupPermissionsTable.ForeignKeys[0].RefTable = GroupsTable
	GroupPermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	PrinciplesRulesTable.ForeignKeys[0].RefTable = RulesTable
	PrinciplesRulesTable.ForeignKeys[1].RefTable = PrinciplesTable
	UserGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserPermissionsTable.ForeignKeys[0].RefTable = UsersTable
	UserPermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
}
