// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/action"
	"defly-defender/ent/predicate"
	"defly-defender/ent/report"
	"defly-defender/ent/rule"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ActionUpdate is the builder for updating Action entities.
type ActionUpdate struct {
	config
	hooks    []Hook
	mutation *ActionMutation
}

// Where appends a list predicates to the ActionUpdate builder.
func (au *ActionUpdate) Where(ps ...predicate.Action) *ActionUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *ActionUpdate) SetName(s string) *ActionUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *ActionUpdate) SetNillableName(s *string) *ActionUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetType sets the "type" field.
func (au *ActionUpdate) SetType(a action.Type) *ActionUpdate {
	au.mutation.SetType(a)
	return au
}

// SetNillableType sets the "type" field if the given value is not nil.
func (au *ActionUpdate) SetNillableType(a *action.Type) *ActionUpdate {
	if a != nil {
		au.SetType(*a)
	}
	return au
}

// SetConfigurations sets the "configurations" field.
func (au *ActionUpdate) SetConfigurations(m map[string]interface{}) *ActionUpdate {
	au.mutation.SetConfigurations(m)
	return au
}

// ClearConfigurations clears the value of the "configurations" field.
func (au *ActionUpdate) ClearConfigurations() *ActionUpdate {
	au.mutation.ClearConfigurations()
	return au
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (au *ActionUpdate) AddRuleIDs(ids ...uuid.UUID) *ActionUpdate {
	au.mutation.AddRuleIDs(ids...)
	return au
}

// AddRules adds the "rules" edges to the Rule entity.
func (au *ActionUpdate) AddRules(r ...*Rule) *ActionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.AddRuleIDs(ids...)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (au *ActionUpdate) AddReportIDs(ids ...uuid.UUID) *ActionUpdate {
	au.mutation.AddReportIDs(ids...)
	return au
}

// AddReports adds the "reports" edges to the Report entity.
func (au *ActionUpdate) AddReports(r ...*Report) *ActionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.AddReportIDs(ids...)
}

// Mutation returns the ActionMutation object of the builder.
func (au *ActionUpdate) Mutation() *ActionMutation {
	return au.mutation
}

// ClearRules clears all "rules" edges to the Rule entity.
func (au *ActionUpdate) ClearRules() *ActionUpdate {
	au.mutation.ClearRules()
	return au
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (au *ActionUpdate) RemoveRuleIDs(ids ...uuid.UUID) *ActionUpdate {
	au.mutation.RemoveRuleIDs(ids...)
	return au
}

// RemoveRules removes "rules" edges to Rule entities.
func (au *ActionUpdate) RemoveRules(r ...*Rule) *ActionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.RemoveRuleIDs(ids...)
}

// ClearReports clears all "reports" edges to the Report entity.
func (au *ActionUpdate) ClearReports() *ActionUpdate {
	au.mutation.ClearReports()
	return au
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (au *ActionUpdate) RemoveReportIDs(ids ...uuid.UUID) *ActionUpdate {
	au.mutation.RemoveReportIDs(ids...)
	return au
}

// RemoveReports removes "reports" edges to Report entities.
func (au *ActionUpdate) RemoveReports(r ...*Report) *ActionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.RemoveReportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ActionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ActionUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ActionUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ActionUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *ActionUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := action.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Action.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.GetType(); ok {
		if err := action.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Action.type": %w`, err)}
		}
	}
	return nil
}

func (au *ActionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(action.Table, action.Columns, sqlgraph.NewFieldSpec(action.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(action.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.GetType(); ok {
		_spec.SetField(action.FieldType, field.TypeEnum, value)
	}
	if value, ok := au.mutation.Configurations(); ok {
		_spec.SetField(action.FieldConfigurations, field.TypeJSON, value)
	}
	if au.mutation.ConfigurationsCleared() {
		_spec.ClearField(action.FieldConfigurations, field.TypeJSON)
	}
	if au.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedRulesIDs(); len(nodes) > 0 && !au.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedReportsIDs(); len(nodes) > 0 && !au.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{action.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ActionUpdateOne is the builder for updating a single Action entity.
type ActionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActionMutation
}

// SetName sets the "name" field.
func (auo *ActionUpdateOne) SetName(s string) *ActionUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *ActionUpdateOne) SetNillableName(s *string) *ActionUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetType sets the "type" field.
func (auo *ActionUpdateOne) SetType(a action.Type) *ActionUpdateOne {
	auo.mutation.SetType(a)
	return auo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (auo *ActionUpdateOne) SetNillableType(a *action.Type) *ActionUpdateOne {
	if a != nil {
		auo.SetType(*a)
	}
	return auo
}

// SetConfigurations sets the "configurations" field.
func (auo *ActionUpdateOne) SetConfigurations(m map[string]interface{}) *ActionUpdateOne {
	auo.mutation.SetConfigurations(m)
	return auo
}

// ClearConfigurations clears the value of the "configurations" field.
func (auo *ActionUpdateOne) ClearConfigurations() *ActionUpdateOne {
	auo.mutation.ClearConfigurations()
	return auo
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (auo *ActionUpdateOne) AddRuleIDs(ids ...uuid.UUID) *ActionUpdateOne {
	auo.mutation.AddRuleIDs(ids...)
	return auo
}

// AddRules adds the "rules" edges to the Rule entity.
func (auo *ActionUpdateOne) AddRules(r ...*Rule) *ActionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.AddRuleIDs(ids...)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (auo *ActionUpdateOne) AddReportIDs(ids ...uuid.UUID) *ActionUpdateOne {
	auo.mutation.AddReportIDs(ids...)
	return auo
}

// AddReports adds the "reports" edges to the Report entity.
func (auo *ActionUpdateOne) AddReports(r ...*Report) *ActionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.AddReportIDs(ids...)
}

// Mutation returns the ActionMutation object of the builder.
func (auo *ActionUpdateOne) Mutation() *ActionMutation {
	return auo.mutation
}

// ClearRules clears all "rules" edges to the Rule entity.
func (auo *ActionUpdateOne) ClearRules() *ActionUpdateOne {
	auo.mutation.ClearRules()
	return auo
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (auo *ActionUpdateOne) RemoveRuleIDs(ids ...uuid.UUID) *ActionUpdateOne {
	auo.mutation.RemoveRuleIDs(ids...)
	return auo
}

// RemoveRules removes "rules" edges to Rule entities.
func (auo *ActionUpdateOne) RemoveRules(r ...*Rule) *ActionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.RemoveRuleIDs(ids...)
}

// ClearReports clears all "reports" edges to the Report entity.
func (auo *ActionUpdateOne) ClearReports() *ActionUpdateOne {
	auo.mutation.ClearReports()
	return auo
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (auo *ActionUpdateOne) RemoveReportIDs(ids ...uuid.UUID) *ActionUpdateOne {
	auo.mutation.RemoveReportIDs(ids...)
	return auo
}

// RemoveReports removes "reports" edges to Report entities.
func (auo *ActionUpdateOne) RemoveReports(r ...*Report) *ActionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.RemoveReportIDs(ids...)
}

// Where appends a list predicates to the ActionUpdate builder.
func (auo *ActionUpdateOne) Where(ps ...predicate.Action) *ActionUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ActionUpdateOne) Select(field string, fields ...string) *ActionUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Action entity.
func (auo *ActionUpdateOne) Save(ctx context.Context) (*Action, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ActionUpdateOne) SaveX(ctx context.Context) *Action {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ActionUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ActionUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *ActionUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := action.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Action.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.GetType(); ok {
		if err := action.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Action.type": %w`, err)}
		}
	}
	return nil
}

func (auo *ActionUpdateOne) sqlSave(ctx context.Context) (_node *Action, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(action.Table, action.Columns, sqlgraph.NewFieldSpec(action.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Action.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, action.FieldID)
		for _, f := range fields {
			if !action.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != action.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(action.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.GetType(); ok {
		_spec.SetField(action.FieldType, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.Configurations(); ok {
		_spec.SetField(action.FieldConfigurations, field.TypeJSON, value)
	}
	if auo.mutation.ConfigurationsCleared() {
		_spec.ClearField(action.FieldConfigurations, field.TypeJSON)
	}
	if auo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedRulesIDs(); len(nodes) > 0 && !auo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   action.RulesTable,
			Columns: action.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedReportsIDs(); len(nodes) > 0 && !auo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.ReportsTable,
			Columns: []string{action.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Action{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{action.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
