// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/decision"
	"defly-defender/ent/predicate"
	"defly-defender/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DecisionUpdate is the builder for updating Decision entities.
type DecisionUpdate struct {
	config
	hooks    []Hook
	mutation *DecisionMutation
}

// Where appends a list predicates to the DecisionUpdate builder.
func (du *DecisionUpdate) Where(ps ...predicate.Decision) *DecisionUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DecisionUpdate) SetName(s string) *DecisionUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableName(s *string) *DecisionUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetDirection sets the "direction" field.
func (du *DecisionUpdate) SetDirection(d decision.Direction) *DecisionUpdate {
	du.mutation.SetDirection(d)
	return du
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableDirection(d *decision.Direction) *DecisionUpdate {
	if d != nil {
		du.SetDirection(*d)
	}
	return du
}

// SetCondition sets the "condition" field.
func (du *DecisionUpdate) SetCondition(d decision.Condition) *DecisionUpdate {
	du.mutation.SetCondition(d)
	return du
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableCondition(d *decision.Condition) *DecisionUpdate {
	if d != nil {
		du.SetCondition(*d)
	}
	return du
}

// SetScore sets the "score" field.
func (du *DecisionUpdate) SetScore(f float64) *DecisionUpdate {
	du.mutation.ResetScore()
	du.mutation.SetScore(f)
	return du
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableScore(f *float64) *DecisionUpdate {
	if f != nil {
		du.SetScore(*f)
	}
	return du
}

// AddScore adds f to the "score" field.
func (du *DecisionUpdate) AddScore(f float64) *DecisionUpdate {
	du.mutation.AddScore(f)
	return du
}

// SetAction sets the "action" field.
func (du *DecisionUpdate) SetAction(d decision.Action) *DecisionUpdate {
	du.mutation.SetAction(d)
	return du
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableAction(d *decision.Action) *DecisionUpdate {
	if d != nil {
		du.SetAction(*d)
	}
	return du
}

// SetConfigurations sets the "configurations" field.
func (du *DecisionUpdate) SetConfigurations(m map[string]interface{}) *DecisionUpdate {
	du.mutation.SetConfigurations(m)
	return du
}

// ClearConfigurations clears the value of the "configurations" field.
func (du *DecisionUpdate) ClearConfigurations() *DecisionUpdate {
	du.mutation.ClearConfigurations()
	return du
}

// SetDescription sets the "description" field.
func (du *DecisionUpdate) SetDescription(s string) *DecisionUpdate {
	du.mutation.SetDescription(s)
	return du
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableDescription(s *string) *DecisionUpdate {
	if s != nil {
		du.SetDescription(*s)
	}
	return du
}

// ClearDescription clears the value of the "description" field.
func (du *DecisionUpdate) ClearDescription() *DecisionUpdate {
	du.mutation.ClearDescription()
	return du
}

// SetCreatedBy sets the "created_by" field.
func (du *DecisionUpdate) SetCreatedBy(u uuid.UUID) *DecisionUpdate {
	du.mutation.SetCreatedBy(u)
	return du
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableCreatedBy(u *uuid.UUID) *DecisionUpdate {
	if u != nil {
		du.SetCreatedBy(*u)
	}
	return du
}

// ClearCreatedBy clears the value of the "created_by" field.
func (du *DecisionUpdate) ClearCreatedBy() *DecisionUpdate {
	du.mutation.ClearCreatedBy()
	return du
}

// SetIsLocked sets the "is_locked" field.
func (du *DecisionUpdate) SetIsLocked(b bool) *DecisionUpdate {
	du.mutation.SetIsLocked(b)
	return du
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableIsLocked(b *bool) *DecisionUpdate {
	if b != nil {
		du.SetIsLocked(*b)
	}
	return du
}

// SetCreatedAt sets the "created_at" field.
func (du *DecisionUpdate) SetCreatedAt(t time.Time) *DecisionUpdate {
	du.mutation.SetCreatedAt(t)
	return du
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (du *DecisionUpdate) SetNillableCreatedAt(t *time.Time) *DecisionUpdate {
	if t != nil {
		du.SetCreatedAt(*t)
	}
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DecisionUpdate) SetUpdatedAt(t time.Time) *DecisionUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (du *DecisionUpdate) SetCreatorID(id uuid.UUID) *DecisionUpdate {
	du.mutation.SetCreatorID(id)
	return du
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (du *DecisionUpdate) SetNillableCreatorID(id *uuid.UUID) *DecisionUpdate {
	if id != nil {
		du = du.SetCreatorID(*id)
	}
	return du
}

// SetCreator sets the "creator" edge to the User entity.
func (du *DecisionUpdate) SetCreator(u *User) *DecisionUpdate {
	return du.SetCreatorID(u.ID)
}

// Mutation returns the DecisionMutation object of the builder.
func (du *DecisionUpdate) Mutation() *DecisionMutation {
	return du.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (du *DecisionUpdate) ClearCreator() *DecisionUpdate {
	du.mutation.ClearCreator()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DecisionUpdate) Save(ctx context.Context) (int, error) {
	du.defaults()
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DecisionUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DecisionUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DecisionUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DecisionUpdate) defaults() {
	if _, ok := du.mutation.UpdatedAt(); !ok {
		v := decision.UpdateDefaultUpdatedAt()
		du.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DecisionUpdate) check() error {
	if v, ok := du.mutation.Name(); ok {
		if err := decision.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Decision.name": %w`, err)}
		}
	}
	if v, ok := du.mutation.Direction(); ok {
		if err := decision.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Decision.direction": %w`, err)}
		}
	}
	if v, ok := du.mutation.Condition(); ok {
		if err := decision.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Decision.condition": %w`, err)}
		}
	}
	if v, ok := du.mutation.Action(); ok {
		if err := decision.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Decision.action": %w`, err)}
		}
	}
	return nil
}

func (du *DecisionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(decision.Table, decision.Columns, sqlgraph.NewFieldSpec(decision.FieldID, field.TypeUUID))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(decision.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.Direction(); ok {
		_spec.SetField(decision.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := du.mutation.Condition(); ok {
		_spec.SetField(decision.FieldCondition, field.TypeEnum, value)
	}
	if value, ok := du.mutation.Score(); ok {
		_spec.SetField(decision.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.AddedScore(); ok {
		_spec.AddField(decision.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.Action(); ok {
		_spec.SetField(decision.FieldAction, field.TypeEnum, value)
	}
	if value, ok := du.mutation.Configurations(); ok {
		_spec.SetField(decision.FieldConfigurations, field.TypeJSON, value)
	}
	if du.mutation.ConfigurationsCleared() {
		_spec.ClearField(decision.FieldConfigurations, field.TypeJSON)
	}
	if value, ok := du.mutation.Description(); ok {
		_spec.SetField(decision.FieldDescription, field.TypeString, value)
	}
	if du.mutation.DescriptionCleared() {
		_spec.ClearField(decision.FieldDescription, field.TypeString)
	}
	if value, ok := du.mutation.IsLocked(); ok {
		_spec.SetField(decision.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := du.mutation.CreatedAt(); ok {
		_spec.SetField(decision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(decision.FieldUpdatedAt, field.TypeTime, value)
	}
	if du.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.CreatorTable,
			Columns: []string{decision.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.CreatorTable,
			Columns: []string{decision.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{decision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DecisionUpdateOne is the builder for updating a single Decision entity.
type DecisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DecisionMutation
}

// SetName sets the "name" field.
func (duo *DecisionUpdateOne) SetName(s string) *DecisionUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableName(s *string) *DecisionUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetDirection sets the "direction" field.
func (duo *DecisionUpdateOne) SetDirection(d decision.Direction) *DecisionUpdateOne {
	duo.mutation.SetDirection(d)
	return duo
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableDirection(d *decision.Direction) *DecisionUpdateOne {
	if d != nil {
		duo.SetDirection(*d)
	}
	return duo
}

// SetCondition sets the "condition" field.
func (duo *DecisionUpdateOne) SetCondition(d decision.Condition) *DecisionUpdateOne {
	duo.mutation.SetCondition(d)
	return duo
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableCondition(d *decision.Condition) *DecisionUpdateOne {
	if d != nil {
		duo.SetCondition(*d)
	}
	return duo
}

// SetScore sets the "score" field.
func (duo *DecisionUpdateOne) SetScore(f float64) *DecisionUpdateOne {
	duo.mutation.ResetScore()
	duo.mutation.SetScore(f)
	return duo
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableScore(f *float64) *DecisionUpdateOne {
	if f != nil {
		duo.SetScore(*f)
	}
	return duo
}

// AddScore adds f to the "score" field.
func (duo *DecisionUpdateOne) AddScore(f float64) *DecisionUpdateOne {
	duo.mutation.AddScore(f)
	return duo
}

// SetAction sets the "action" field.
func (duo *DecisionUpdateOne) SetAction(d decision.Action) *DecisionUpdateOne {
	duo.mutation.SetAction(d)
	return duo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableAction(d *decision.Action) *DecisionUpdateOne {
	if d != nil {
		duo.SetAction(*d)
	}
	return duo
}

// SetConfigurations sets the "configurations" field.
func (duo *DecisionUpdateOne) SetConfigurations(m map[string]interface{}) *DecisionUpdateOne {
	duo.mutation.SetConfigurations(m)
	return duo
}

// ClearConfigurations clears the value of the "configurations" field.
func (duo *DecisionUpdateOne) ClearConfigurations() *DecisionUpdateOne {
	duo.mutation.ClearConfigurations()
	return duo
}

// SetDescription sets the "description" field.
func (duo *DecisionUpdateOne) SetDescription(s string) *DecisionUpdateOne {
	duo.mutation.SetDescription(s)
	return duo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableDescription(s *string) *DecisionUpdateOne {
	if s != nil {
		duo.SetDescription(*s)
	}
	return duo
}

// ClearDescription clears the value of the "description" field.
func (duo *DecisionUpdateOne) ClearDescription() *DecisionUpdateOne {
	duo.mutation.ClearDescription()
	return duo
}

// SetCreatedBy sets the "created_by" field.
func (duo *DecisionUpdateOne) SetCreatedBy(u uuid.UUID) *DecisionUpdateOne {
	duo.mutation.SetCreatedBy(u)
	return duo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableCreatedBy(u *uuid.UUID) *DecisionUpdateOne {
	if u != nil {
		duo.SetCreatedBy(*u)
	}
	return duo
}

// ClearCreatedBy clears the value of the "created_by" field.
func (duo *DecisionUpdateOne) ClearCreatedBy() *DecisionUpdateOne {
	duo.mutation.ClearCreatedBy()
	return duo
}

// SetIsLocked sets the "is_locked" field.
func (duo *DecisionUpdateOne) SetIsLocked(b bool) *DecisionUpdateOne {
	duo.mutation.SetIsLocked(b)
	return duo
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableIsLocked(b *bool) *DecisionUpdateOne {
	if b != nil {
		duo.SetIsLocked(*b)
	}
	return duo
}

// SetCreatedAt sets the "created_at" field.
func (duo *DecisionUpdateOne) SetCreatedAt(t time.Time) *DecisionUpdateOne {
	duo.mutation.SetCreatedAt(t)
	return duo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableCreatedAt(t *time.Time) *DecisionUpdateOne {
	if t != nil {
		duo.SetCreatedAt(*t)
	}
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DecisionUpdateOne) SetUpdatedAt(t time.Time) *DecisionUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (duo *DecisionUpdateOne) SetCreatorID(id uuid.UUID) *DecisionUpdateOne {
	duo.mutation.SetCreatorID(id)
	return duo
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableCreatorID(id *uuid.UUID) *DecisionUpdateOne {
	if id != nil {
		duo = duo.SetCreatorID(*id)
	}
	return duo
}

// SetCreator sets the "creator" edge to the User entity.
func (duo *DecisionUpdateOne) SetCreator(u *User) *DecisionUpdateOne {
	return duo.SetCreatorID(u.ID)
}

// Mutation returns the DecisionMutation object of the builder.
func (duo *DecisionUpdateOne) Mutation() *DecisionMutation {
	return duo.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (duo *DecisionUpdateOne) ClearCreator() *DecisionUpdateOne {
	duo.mutation.ClearCreator()
	return duo
}

// Where appends a list predicates to the DecisionUpdate builder.
func (duo *DecisionUpdateOne) Where(ps ...predicate.Decision) *DecisionUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DecisionUpdateOne) Select(field string, fields ...string) *DecisionUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Decision entity.
func (duo *DecisionUpdateOne) Save(ctx context.Context) (*Decision, error) {
	duo.defaults()
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DecisionUpdateOne) SaveX(ctx context.Context) *Decision {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DecisionUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DecisionUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DecisionUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdatedAt(); !ok {
		v := decision.UpdateDefaultUpdatedAt()
		duo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DecisionUpdateOne) check() error {
	if v, ok := duo.mutation.Name(); ok {
		if err := decision.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Decision.name": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Direction(); ok {
		if err := decision.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Decision.direction": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Condition(); ok {
		if err := decision.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Decision.condition": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Action(); ok {
		if err := decision.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Decision.action": %w`, err)}
		}
	}
	return nil
}

func (duo *DecisionUpdateOne) sqlSave(ctx context.Context) (_node *Decision, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(decision.Table, decision.Columns, sqlgraph.NewFieldSpec(decision.FieldID, field.TypeUUID))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Decision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, decision.FieldID)
		for _, f := range fields {
			if !decision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != decision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(decision.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.Direction(); ok {
		_spec.SetField(decision.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := duo.mutation.Condition(); ok {
		_spec.SetField(decision.FieldCondition, field.TypeEnum, value)
	}
	if value, ok := duo.mutation.Score(); ok {
		_spec.SetField(decision.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.AddedScore(); ok {
		_spec.AddField(decision.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.Action(); ok {
		_spec.SetField(decision.FieldAction, field.TypeEnum, value)
	}
	if value, ok := duo.mutation.Configurations(); ok {
		_spec.SetField(decision.FieldConfigurations, field.TypeJSON, value)
	}
	if duo.mutation.ConfigurationsCleared() {
		_spec.ClearField(decision.FieldConfigurations, field.TypeJSON)
	}
	if value, ok := duo.mutation.Description(); ok {
		_spec.SetField(decision.FieldDescription, field.TypeString, value)
	}
	if duo.mutation.DescriptionCleared() {
		_spec.ClearField(decision.FieldDescription, field.TypeString)
	}
	if value, ok := duo.mutation.IsLocked(); ok {
		_spec.SetField(decision.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := duo.mutation.CreatedAt(); ok {
		_spec.SetField(decision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(decision.FieldUpdatedAt, field.TypeTime, value)
	}
	if duo.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.CreatorTable,
			Columns: []string{decision.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.CreatorTable,
			Columns: []string{decision.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Decision{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{decision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
