// Code generated by ent, DO NOT EDIT.

package ent

import (
	"defly-defender/ent/defender"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Defender is the model entity for the Defender schema.
type Defender struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ProxyPort holds the value of the "proxy_port" field.
	ProxyPort *int `json:"proxy_port,omitempty"`
	// Status holds the value of the "status" field.
	Status *defender.Status `json:"status,omitempty"`
	// Details holds the value of the "details" field.
	Details map[string]interface{} `json:"details,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DefenderQuery when eager-loading is set.
	Edges        DefenderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DefenderEdges holds the relations/edges for other nodes in the graph.
type DefenderEdges struct {
	// Principles holds the value of the principles edge.
	Principles []*Principle `json:"principles,omitempty"`
	// Decisions holds the value of the decisions edge.
	Decisions []*Decision `json:"decisions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PrinciplesOrErr returns the Principles value or an error if the edge
// was not loaded in eager-loading.
func (e DefenderEdges) PrinciplesOrErr() ([]*Principle, error) {
	if e.loadedTypes[0] {
		return e.Principles, nil
	}
	return nil, &NotLoadedError{edge: "principles"}
}

// DecisionsOrErr returns the Decisions value or an error if the edge
// was not loaded in eager-loading.
func (e DefenderEdges) DecisionsOrErr() ([]*Decision, error) {
	if e.loadedTypes[1] {
		return e.Decisions, nil
	}
	return nil, &NotLoadedError{edge: "decisions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Defender) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case defender.FieldDetails:
			values[i] = new([]byte)
		case defender.FieldProxyPort:
			values[i] = new(sql.NullInt64)
		case defender.FieldName, defender.FieldStatus:
			values[i] = new(sql.NullString)
		case defender.FieldCreatedAt, defender.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case defender.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Defender fields.
func (d *Defender) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case defender.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				d.ID = *value
			}
		case defender.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case defender.FieldProxyPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_port", values[i])
			} else if value.Valid {
				d.ProxyPort = new(int)
				*d.ProxyPort = int(value.Int64)
			}
		case defender.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				d.Status = new(defender.Status)
				*d.Status = defender.Status(value.String)
			}
		case defender.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &d.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		case defender.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				d.CreatedAt = value.Time
			}
		case defender.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				d.UpdatedAt = value.Time
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Defender.
// This includes values selected through modifiers, order, etc.
func (d *Defender) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryPrinciples queries the "principles" edge of the Defender entity.
func (d *Defender) QueryPrinciples() *PrincipleQuery {
	return NewDefenderClient(d.config).QueryPrinciples(d)
}

// QueryDecisions queries the "decisions" edge of the Defender entity.
func (d *Defender) QueryDecisions() *DecisionQuery {
	return NewDefenderClient(d.config).QueryDecisions(d)
}

// Update returns a builder for updating this Defender.
// Note that you need to call Defender.Unwrap() before calling this method if this Defender
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Defender) Update() *DefenderUpdateOne {
	return NewDefenderClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Defender entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Defender) Unwrap() *Defender {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Defender is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Defender) String() string {
	var builder strings.Builder
	builder.WriteString("Defender(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteString(", ")
	if v := d.ProxyPort; v != nil {
		builder.WriteString("proxy_port=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := d.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", d.Details))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(d.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(d.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Defenders is a parsable slice of Defender.
type Defenders []*Defender
