// Code generated by ent, DO NOT EDIT.

package ent

import (
	"defly-defender/ent/engine"
	"defly-defender/ent/user"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Engine is the model entity for the Engine schema.
type Engine struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// InputDatatype holds the value of the "input_datatype" field.
	InputDatatype engine.InputDatatype `json:"input_datatype,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Configurations holds the value of the "configurations" field.
	Configurations map[string]interface{} `json:"configurations,omitempty"`
	// OutputDatatype holds the value of the "output_datatype" field.
	OutputDatatype engine.OutputDatatype `json:"output_datatype,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// IsLocked holds the value of the "is_locked" field.
	IsLocked bool `json:"is_locked,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EngineQuery when eager-loading is set.
	Edges        EngineEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EngineEdges holds the relations/edges for other nodes in the graph.
type EngineEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Targets holds the value of the targets edge.
	Targets []*Target `json:"targets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EngineEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// TargetsOrErr returns the Targets value or an error if the edge
// was not loaded in eager-loading.
func (e EngineEdges) TargetsOrErr() ([]*Target, error) {
	if e.loadedTypes[1] {
		return e.Targets, nil
	}
	return nil, &NotLoadedError{edge: "targets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Engine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case engine.FieldCreatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case engine.FieldConfigurations:
			values[i] = new([]byte)
		case engine.FieldIsLocked:
			values[i] = new(sql.NullBool)
		case engine.FieldName, engine.FieldInputDatatype, engine.FieldType, engine.FieldOutputDatatype, engine.FieldDescription:
			values[i] = new(sql.NullString)
		case engine.FieldCreatedAt, engine.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case engine.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Engine fields.
func (e *Engine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case engine.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				e.ID = *value
			}
		case engine.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				e.Name = value.String
			}
		case engine.FieldInputDatatype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_datatype", values[i])
			} else if value.Valid {
				e.InputDatatype = engine.InputDatatype(value.String)
			}
		case engine.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				e.Type = value.String
			}
		case engine.FieldConfigurations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field configurations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &e.Configurations); err != nil {
					return fmt.Errorf("unmarshal field configurations: %w", err)
				}
			}
		case engine.FieldOutputDatatype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_datatype", values[i])
			} else if value.Valid {
				e.OutputDatatype = engine.OutputDatatype(value.String)
			}
		case engine.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				e.Description = new(string)
				*e.Description = value.String
			}
		case engine.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				e.CreatedBy = new(uuid.UUID)
				*e.CreatedBy = *value.S.(*uuid.UUID)
			}
		case engine.FieldIsLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_locked", values[i])
			} else if value.Valid {
				e.IsLocked = value.Bool
			}
		case engine.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case engine.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Engine.
// This includes values selected through modifiers, order, etc.
func (e *Engine) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Engine entity.
func (e *Engine) QueryCreator() *UserQuery {
	return NewEngineClient(e.config).QueryCreator(e)
}

// QueryTargets queries the "targets" edge of the Engine entity.
func (e *Engine) QueryTargets() *TargetQuery {
	return NewEngineClient(e.config).QueryTargets(e)
}

// Update returns a builder for updating this Engine.
// Note that you need to call Engine.Unwrap() before calling this method if this Engine
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Engine) Update() *EngineUpdateOne {
	return NewEngineClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Engine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Engine) Unwrap() *Engine {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Engine is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Engine) String() string {
	var builder strings.Builder
	builder.WriteString("Engine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("name=")
	builder.WriteString(e.Name)
	builder.WriteString(", ")
	builder.WriteString("input_datatype=")
	builder.WriteString(fmt.Sprintf("%v", e.InputDatatype))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(e.Type)
	builder.WriteString(", ")
	builder.WriteString("configurations=")
	builder.WriteString(fmt.Sprintf("%v", e.Configurations))
	builder.WriteString(", ")
	builder.WriteString("output_datatype=")
	builder.WriteString(fmt.Sprintf("%v", e.OutputDatatype))
	builder.WriteString(", ")
	if v := e.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := e.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_locked=")
	builder.WriteString(fmt.Sprintf("%v", e.IsLocked))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Engines is a parsable slice of Engine.
type Engines []*Engine
