// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/defender"
	"defly-defender/ent/predicate"
	"defly-defender/ent/principle"
	"defly-defender/ent/rule"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrincipleUpdate is the builder for updating Principle entities.
type PrincipleUpdate struct {
	config
	hooks    []Hook
	mutation *PrincipleMutation
}

// Where appends a list predicates to the PrincipleUpdate builder.
func (pu *PrincipleUpdate) Where(ps ...predicate.Principle) *PrincipleUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *PrincipleUpdate) SetName(s string) *PrincipleUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *PrincipleUpdate) SetNillableName(s *string) *PrincipleUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetLevel sets the "level" field.
func (pu *PrincipleUpdate) SetLevel(u uint64) *PrincipleUpdate {
	pu.mutation.ResetLevel()
	pu.mutation.SetLevel(u)
	return pu
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (pu *PrincipleUpdate) SetNillableLevel(u *uint64) *PrincipleUpdate {
	if u != nil {
		pu.SetLevel(*u)
	}
	return pu
}

// AddLevel adds u to the "level" field.
func (pu *PrincipleUpdate) AddLevel(u int64) *PrincipleUpdate {
	pu.mutation.AddLevel(u)
	return pu
}

// SetPhase sets the "phase" field.
func (pu *PrincipleUpdate) SetPhase(i int) *PrincipleUpdate {
	pu.mutation.ResetPhase()
	pu.mutation.SetPhase(i)
	return pu
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (pu *PrincipleUpdate) SetNillablePhase(i *int) *PrincipleUpdate {
	if i != nil {
		pu.SetPhase(*i)
	}
	return pu
}

// AddPhase adds i to the "phase" field.
func (pu *PrincipleUpdate) AddPhase(i int) *PrincipleUpdate {
	pu.mutation.AddPhase(i)
	return pu
}

// SetIsApplied sets the "is_applied" field.
func (pu *PrincipleUpdate) SetIsApplied(b bool) *PrincipleUpdate {
	pu.mutation.SetIsApplied(b)
	return pu
}

// SetNillableIsApplied sets the "is_applied" field if the given value is not nil.
func (pu *PrincipleUpdate) SetNillableIsApplied(b *bool) *PrincipleUpdate {
	if b != nil {
		pu.SetIsApplied(*b)
	}
	return pu
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (pu *PrincipleUpdate) AddRuleIDs(ids ...uuid.UUID) *PrincipleUpdate {
	pu.mutation.AddRuleIDs(ids...)
	return pu
}

// AddRules adds the "rules" edges to the Rule entity.
func (pu *PrincipleUpdate) AddRules(r ...*Rule) *PrincipleUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pu.AddRuleIDs(ids...)
}

// AddDefenderIDs adds the "defenders" edge to the Defender entity by IDs.
func (pu *PrincipleUpdate) AddDefenderIDs(ids ...uuid.UUID) *PrincipleUpdate {
	pu.mutation.AddDefenderIDs(ids...)
	return pu
}

// AddDefenders adds the "defenders" edges to the Defender entity.
func (pu *PrincipleUpdate) AddDefenders(d ...*Defender) *PrincipleUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.AddDefenderIDs(ids...)
}

// Mutation returns the PrincipleMutation object of the builder.
func (pu *PrincipleUpdate) Mutation() *PrincipleMutation {
	return pu.mutation
}

// ClearRules clears all "rules" edges to the Rule entity.
func (pu *PrincipleUpdate) ClearRules() *PrincipleUpdate {
	pu.mutation.ClearRules()
	return pu
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (pu *PrincipleUpdate) RemoveRuleIDs(ids ...uuid.UUID) *PrincipleUpdate {
	pu.mutation.RemoveRuleIDs(ids...)
	return pu
}

// RemoveRules removes "rules" edges to Rule entities.
func (pu *PrincipleUpdate) RemoveRules(r ...*Rule) *PrincipleUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pu.RemoveRuleIDs(ids...)
}

// ClearDefenders clears all "defenders" edges to the Defender entity.
func (pu *PrincipleUpdate) ClearDefenders() *PrincipleUpdate {
	pu.mutation.ClearDefenders()
	return pu
}

// RemoveDefenderIDs removes the "defenders" edge to Defender entities by IDs.
func (pu *PrincipleUpdate) RemoveDefenderIDs(ids ...uuid.UUID) *PrincipleUpdate {
	pu.mutation.RemoveDefenderIDs(ids...)
	return pu
}

// RemoveDefenders removes "defenders" edges to Defender entities.
func (pu *PrincipleUpdate) RemoveDefenders(d ...*Defender) *PrincipleUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.RemoveDefenderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PrincipleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PrincipleUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PrincipleUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PrincipleUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PrincipleUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := principle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Principle.name": %w`, err)}
		}
	}
	return nil
}

func (pu *PrincipleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(principle.Table, principle.Columns, sqlgraph.NewFieldSpec(principle.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(principle.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Level(); ok {
		_spec.SetField(principle.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := pu.mutation.AddedLevel(); ok {
		_spec.AddField(principle.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := pu.mutation.Phase(); ok {
		_spec.SetField(principle.FieldPhase, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPhase(); ok {
		_spec.AddField(principle.FieldPhase, field.TypeInt, value)
	}
	if value, ok := pu.mutation.IsApplied(); ok {
		_spec.SetField(principle.FieldIsApplied, field.TypeBool, value)
	}
	if pu.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedRulesIDs(); len(nodes) > 0 && !pu.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.DefendersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedDefendersIDs(); len(nodes) > 0 && !pu.mutation.DefendersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.DefendersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{principle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PrincipleUpdateOne is the builder for updating a single Principle entity.
type PrincipleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrincipleMutation
}

// SetName sets the "name" field.
func (puo *PrincipleUpdateOne) SetName(s string) *PrincipleUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *PrincipleUpdateOne) SetNillableName(s *string) *PrincipleUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetLevel sets the "level" field.
func (puo *PrincipleUpdateOne) SetLevel(u uint64) *PrincipleUpdateOne {
	puo.mutation.ResetLevel()
	puo.mutation.SetLevel(u)
	return puo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (puo *PrincipleUpdateOne) SetNillableLevel(u *uint64) *PrincipleUpdateOne {
	if u != nil {
		puo.SetLevel(*u)
	}
	return puo
}

// AddLevel adds u to the "level" field.
func (puo *PrincipleUpdateOne) AddLevel(u int64) *PrincipleUpdateOne {
	puo.mutation.AddLevel(u)
	return puo
}

// SetPhase sets the "phase" field.
func (puo *PrincipleUpdateOne) SetPhase(i int) *PrincipleUpdateOne {
	puo.mutation.ResetPhase()
	puo.mutation.SetPhase(i)
	return puo
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (puo *PrincipleUpdateOne) SetNillablePhase(i *int) *PrincipleUpdateOne {
	if i != nil {
		puo.SetPhase(*i)
	}
	return puo
}

// AddPhase adds i to the "phase" field.
func (puo *PrincipleUpdateOne) AddPhase(i int) *PrincipleUpdateOne {
	puo.mutation.AddPhase(i)
	return puo
}

// SetIsApplied sets the "is_applied" field.
func (puo *PrincipleUpdateOne) SetIsApplied(b bool) *PrincipleUpdateOne {
	puo.mutation.SetIsApplied(b)
	return puo
}

// SetNillableIsApplied sets the "is_applied" field if the given value is not nil.
func (puo *PrincipleUpdateOne) SetNillableIsApplied(b *bool) *PrincipleUpdateOne {
	if b != nil {
		puo.SetIsApplied(*b)
	}
	return puo
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (puo *PrincipleUpdateOne) AddRuleIDs(ids ...uuid.UUID) *PrincipleUpdateOne {
	puo.mutation.AddRuleIDs(ids...)
	return puo
}

// AddRules adds the "rules" edges to the Rule entity.
func (puo *PrincipleUpdateOne) AddRules(r ...*Rule) *PrincipleUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return puo.AddRuleIDs(ids...)
}

// AddDefenderIDs adds the "defenders" edge to the Defender entity by IDs.
func (puo *PrincipleUpdateOne) AddDefenderIDs(ids ...uuid.UUID) *PrincipleUpdateOne {
	puo.mutation.AddDefenderIDs(ids...)
	return puo
}

// AddDefenders adds the "defenders" edges to the Defender entity.
func (puo *PrincipleUpdateOne) AddDefenders(d ...*Defender) *PrincipleUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.AddDefenderIDs(ids...)
}

// Mutation returns the PrincipleMutation object of the builder.
func (puo *PrincipleUpdateOne) Mutation() *PrincipleMutation {
	return puo.mutation
}

// ClearRules clears all "rules" edges to the Rule entity.
func (puo *PrincipleUpdateOne) ClearRules() *PrincipleUpdateOne {
	puo.mutation.ClearRules()
	return puo
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (puo *PrincipleUpdateOne) RemoveRuleIDs(ids ...uuid.UUID) *PrincipleUpdateOne {
	puo.mutation.RemoveRuleIDs(ids...)
	return puo
}

// RemoveRules removes "rules" edges to Rule entities.
func (puo *PrincipleUpdateOne) RemoveRules(r ...*Rule) *PrincipleUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return puo.RemoveRuleIDs(ids...)
}

// ClearDefenders clears all "defenders" edges to the Defender entity.
func (puo *PrincipleUpdateOne) ClearDefenders() *PrincipleUpdateOne {
	puo.mutation.ClearDefenders()
	return puo
}

// RemoveDefenderIDs removes the "defenders" edge to Defender entities by IDs.
func (puo *PrincipleUpdateOne) RemoveDefenderIDs(ids ...uuid.UUID) *PrincipleUpdateOne {
	puo.mutation.RemoveDefenderIDs(ids...)
	return puo
}

// RemoveDefenders removes "defenders" edges to Defender entities.
func (puo *PrincipleUpdateOne) RemoveDefenders(d ...*Defender) *PrincipleUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.RemoveDefenderIDs(ids...)
}

// Where appends a list predicates to the PrincipleUpdate builder.
func (puo *PrincipleUpdateOne) Where(ps ...predicate.Principle) *PrincipleUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PrincipleUpdateOne) Select(field string, fields ...string) *PrincipleUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Principle entity.
func (puo *PrincipleUpdateOne) Save(ctx context.Context) (*Principle, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PrincipleUpdateOne) SaveX(ctx context.Context) *Principle {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PrincipleUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PrincipleUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PrincipleUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := principle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Principle.name": %w`, err)}
		}
	}
	return nil
}

func (puo *PrincipleUpdateOne) sqlSave(ctx context.Context) (_node *Principle, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(principle.Table, principle.Columns, sqlgraph.NewFieldSpec(principle.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Principle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, principle.FieldID)
		for _, f := range fields {
			if !principle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != principle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(principle.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Level(); ok {
		_spec.SetField(principle.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := puo.mutation.AddedLevel(); ok {
		_spec.AddField(principle.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := puo.mutation.Phase(); ok {
		_spec.SetField(principle.FieldPhase, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPhase(); ok {
		_spec.AddField(principle.FieldPhase, field.TypeInt, value)
	}
	if value, ok := puo.mutation.IsApplied(); ok {
		_spec.SetField(principle.FieldIsApplied, field.TypeBool, value)
	}
	if puo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedRulesIDs(); len(nodes) > 0 && !puo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.DefendersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedDefendersIDs(); len(nodes) > 0 && !puo.mutation.DefendersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.DefendersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Principle{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{principle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
