// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/defender"
	"defly-defender/ent/principle"
	"defly-defender/ent/rule"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrincipleCreate is the builder for creating a Principle entity.
type PrincipleCreate struct {
	config
	mutation *PrincipleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PrincipleCreate) SetName(s string) *PrincipleCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetLevel sets the "level" field.
func (pc *PrincipleCreate) SetLevel(u uint64) *PrincipleCreate {
	pc.mutation.SetLevel(u)
	return pc
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (pc *PrincipleCreate) SetNillableLevel(u *uint64) *PrincipleCreate {
	if u != nil {
		pc.SetLevel(*u)
	}
	return pc
}

// SetPhase sets the "phase" field.
func (pc *PrincipleCreate) SetPhase(i int) *PrincipleCreate {
	pc.mutation.SetPhase(i)
	return pc
}

// SetIsApplied sets the "is_applied" field.
func (pc *PrincipleCreate) SetIsApplied(b bool) *PrincipleCreate {
	pc.mutation.SetIsApplied(b)
	return pc
}

// SetNillableIsApplied sets the "is_applied" field if the given value is not nil.
func (pc *PrincipleCreate) SetNillableIsApplied(b *bool) *PrincipleCreate {
	if b != nil {
		pc.SetIsApplied(*b)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PrincipleCreate) SetID(u uuid.UUID) *PrincipleCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PrincipleCreate) SetNillableID(u *uuid.UUID) *PrincipleCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (pc *PrincipleCreate) AddRuleIDs(ids ...uuid.UUID) *PrincipleCreate {
	pc.mutation.AddRuleIDs(ids...)
	return pc
}

// AddRules adds the "rules" edges to the Rule entity.
func (pc *PrincipleCreate) AddRules(r ...*Rule) *PrincipleCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRuleIDs(ids...)
}

// AddDefenderIDs adds the "defenders" edge to the Defender entity by IDs.
func (pc *PrincipleCreate) AddDefenderIDs(ids ...uuid.UUID) *PrincipleCreate {
	pc.mutation.AddDefenderIDs(ids...)
	return pc
}

// AddDefenders adds the "defenders" edges to the Defender entity.
func (pc *PrincipleCreate) AddDefenders(d ...*Defender) *PrincipleCreate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pc.AddDefenderIDs(ids...)
}

// Mutation returns the PrincipleMutation object of the builder.
func (pc *PrincipleCreate) Mutation() *PrincipleMutation {
	return pc.mutation
}

// Save creates the Principle in the database.
func (pc *PrincipleCreate) Save(ctx context.Context) (*Principle, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PrincipleCreate) SaveX(ctx context.Context) *Principle {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PrincipleCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PrincipleCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PrincipleCreate) defaults() {
	if _, ok := pc.mutation.Level(); !ok {
		v := principle.DefaultLevel
		pc.mutation.SetLevel(v)
	}
	if _, ok := pc.mutation.IsApplied(); !ok {
		v := principle.DefaultIsApplied
		pc.mutation.SetIsApplied(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := principle.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PrincipleCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Principle.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := principle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Principle.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Principle.level"`)}
	}
	if _, ok := pc.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "Principle.phase"`)}
	}
	if _, ok := pc.mutation.IsApplied(); !ok {
		return &ValidationError{Name: "is_applied", err: errors.New(`ent: missing required field "Principle.is_applied"`)}
	}
	return nil
}

func (pc *PrincipleCreate) sqlSave(ctx context.Context) (*Principle, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PrincipleCreate) createSpec() (*Principle, *sqlgraph.CreateSpec) {
	var (
		_node = &Principle{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(principle.Table, sqlgraph.NewFieldSpec(principle.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(principle.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Level(); ok {
		_spec.SetField(principle.FieldLevel, field.TypeUint64, value)
		_node.Level = value
	}
	if value, ok := pc.mutation.Phase(); ok {
		_spec.SetField(principle.FieldPhase, field.TypeInt, value)
		_node.Phase = value
	}
	if value, ok := pc.mutation.IsApplied(); ok {
		_spec.SetField(principle.FieldIsApplied, field.TypeBool, value)
		_node.IsApplied = value
	}
	if nodes := pc.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.RulesTable,
			Columns: principle.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.DefendersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   principle.DefendersTable,
			Columns: principle.DefendersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PrincipleCreateBulk is the builder for creating many Principle entities in bulk.
type PrincipleCreateBulk struct {
	config
	err      error
	builders []*PrincipleCreate
}

// Save creates the Principle entities in the database.
func (pcb *PrincipleCreateBulk) Save(ctx context.Context) ([]*Principle, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Principle, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrincipleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PrincipleCreateBulk) SaveX(ctx context.Context) []*Principle {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PrincipleCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PrincipleCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
