// Code generated by ent, DO NOT EDIT.

package ent

import (
	"defly-defender/ent/action"
	"defly-defender/ent/defender"
	"defly-defender/ent/report"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Report is the model entity for the Report schema.
type Report struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Metas holds the value of the "metas" field.
	Metas map[string]interface{} `json:"metas,omitempty"`
	// RequestHeaders holds the value of the "request_headers" field.
	RequestHeaders []map[string]string `json:"request_headers,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody map[string]interface{} `json:"request_body,omitempty"`
	// ResponseHeaders holds the value of the "response_headers" field.
	ResponseHeaders []map[string]string `json:"response_headers,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody map[string]interface{} `json:"response_body,omitempty"`
	// RuleDetails holds the value of the "rule_details" field.
	RuleDetails map[string]interface{} `json:"rule_details,omitempty"`
	// TriggeredBy holds the value of the "triggered_by" field.
	TriggeredBy *uuid.UUID `json:"triggered_by,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReportQuery when eager-loading is set.
	Edges        ReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReportEdges holds the relations/edges for other nodes in the graph.
type ReportEdges struct {
	// TriggeredByAction holds the value of the triggered_by_action edge.
	TriggeredByAction *Action `json:"triggered_by_action,omitempty"`
	// CreatedByDefender holds the value of the created_by_defender edge.
	CreatedByDefender *Defender `json:"created_by_defender,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TriggeredByActionOrErr returns the TriggeredByAction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportEdges) TriggeredByActionOrErr() (*Action, error) {
	if e.TriggeredByAction != nil {
		return e.TriggeredByAction, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: action.Label}
	}
	return nil, &NotLoadedError{edge: "triggered_by_action"}
}

// CreatedByDefenderOrErr returns the CreatedByDefender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportEdges) CreatedByDefenderOrErr() (*Defender, error) {
	if e.CreatedByDefender != nil {
		return e.CreatedByDefender, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: defender.Label}
	}
	return nil, &NotLoadedError{edge: "created_by_defender"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Report) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case report.FieldTriggeredBy, report.FieldCreatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case report.FieldMetas, report.FieldRequestHeaders, report.FieldRequestBody, report.FieldResponseHeaders, report.FieldResponseBody, report.FieldRuleDetails:
			values[i] = new([]byte)
		case report.FieldCreatedAt, report.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case report.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Report fields.
func (r *Report) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case report.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case report.FieldMetas:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metas", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.Metas); err != nil {
					return fmt.Errorf("unmarshal field metas: %w", err)
				}
			}
		case report.FieldRequestHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.RequestHeaders); err != nil {
					return fmt.Errorf("unmarshal field request_headers: %w", err)
				}
			}
		case report.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.RequestBody); err != nil {
					return fmt.Errorf("unmarshal field request_body: %w", err)
				}
			}
		case report.FieldResponseHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.ResponseHeaders); err != nil {
					return fmt.Errorf("unmarshal field response_headers: %w", err)
				}
			}
		case report.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.ResponseBody); err != nil {
					return fmt.Errorf("unmarshal field response_body: %w", err)
				}
			}
		case report.FieldRuleDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rule_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.RuleDetails); err != nil {
					return fmt.Errorf("unmarshal field rule_details: %w", err)
				}
			}
		case report.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				r.TriggeredBy = new(uuid.UUID)
				*r.TriggeredBy = *value.S.(*uuid.UUID)
			}
		case report.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				r.CreatedBy = new(uuid.UUID)
				*r.CreatedBy = *value.S.(*uuid.UUID)
			}
		case report.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case report.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Report.
// This includes values selected through modifiers, order, etc.
func (r *Report) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryTriggeredByAction queries the "triggered_by_action" edge of the Report entity.
func (r *Report) QueryTriggeredByAction() *ActionQuery {
	return NewReportClient(r.config).QueryTriggeredByAction(r)
}

// QueryCreatedByDefender queries the "created_by_defender" edge of the Report entity.
func (r *Report) QueryCreatedByDefender() *DefenderQuery {
	return NewReportClient(r.config).QueryCreatedByDefender(r)
}

// Update returns a builder for updating this Report.
// Note that you need to call Report.Unwrap() before calling this method if this Report
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Report) Update() *ReportUpdateOne {
	return NewReportClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Report entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Report) Unwrap() *Report {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Report is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Report) String() string {
	var builder strings.Builder
	builder.WriteString("Report(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("metas=")
	builder.WriteString(fmt.Sprintf("%v", r.Metas))
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(fmt.Sprintf("%v", r.RequestHeaders))
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", r.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("response_headers=")
	builder.WriteString(fmt.Sprintf("%v", r.ResponseHeaders))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", r.ResponseBody))
	builder.WriteString(", ")
	builder.WriteString("rule_details=")
	builder.WriteString(fmt.Sprintf("%v", r.RuleDetails))
	builder.WriteString(", ")
	if v := r.TriggeredBy; v != nil {
		builder.WriteString("triggered_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := r.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Reports is a parsable slice of Report.
type Reports []*Report
