// Code generated by ent, DO NOT EDIT.

package ent

import (
	"defly-defender/ent/rule"
	"defly-defender/ent/target"
	"defly-defender/ent/wordlist"
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Rule is the model entity for the Rule schema.
type Rule struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase int `json:"phase,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID *uuid.UUID `json:"target_id,omitempty"`
	// Comparator holds the value of the "comparator" field.
	Comparator string `json:"comparator,omitempty"`
	// IsInversed holds the value of the "is_inversed" field.
	IsInversed bool `json:"is_inversed,omitempty"`
	// Configurations holds the value of the "configurations" field.
	Configurations map[string]interface{} `json:"configurations,omitempty"`
	// WordlistID holds the value of the "wordlist_id" field.
	WordlistID *uuid.UUID `json:"wordlist_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RuleQuery when eager-loading is set.
	Edges        RuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RuleEdges holds the relations/edges for other nodes in the graph.
type RuleEdges struct {
	// Target holds the value of the target edge.
	Target *Target `json:"target,omitempty"`
	// Wordlist holds the value of the wordlist edge.
	Wordlist *Wordlist `json:"wordlist,omitempty"`
	// Actions holds the value of the actions edge.
	Actions []*Action `json:"actions,omitempty"`
	// Principles holds the value of the principles edge.
	Principles []*Principle `json:"principles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleEdges) TargetOrErr() (*Target, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: target.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// WordlistOrErr returns the Wordlist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleEdges) WordlistOrErr() (*Wordlist, error) {
	if e.Wordlist != nil {
		return e.Wordlist, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: wordlist.Label}
	}
	return nil, &NotLoadedError{edge: "wordlist"}
}

// ActionsOrErr returns the Actions value or an error if the edge
// was not loaded in eager-loading.
func (e RuleEdges) ActionsOrErr() ([]*Action, error) {
	if e.loadedTypes[2] {
		return e.Actions, nil
	}
	return nil, &NotLoadedError{edge: "actions"}
}

// PrinciplesOrErr returns the Principles value or an error if the edge
// was not loaded in eager-loading.
func (e RuleEdges) PrinciplesOrErr() ([]*Principle, error) {
	if e.loadedTypes[3] {
		return e.Principles, nil
	}
	return nil, &NotLoadedError{edge: "principles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rule.FieldTargetID, rule.FieldWordlistID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rule.FieldConfigurations:
			values[i] = new([]byte)
		case rule.FieldIsInversed:
			values[i] = new(sql.NullBool)
		case rule.FieldPhase:
			values[i] = new(sql.NullInt64)
		case rule.FieldName, rule.FieldComparator:
			values[i] = new(sql.NullString)
		case rule.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rule fields.
func (r *Rule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rule.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case rule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				r.Name = value.String
			}
		case rule.FieldPhase:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				r.Phase = int(value.Int64)
			}
		case rule.FieldTargetID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				r.TargetID = new(uuid.UUID)
				*r.TargetID = *value.S.(*uuid.UUID)
			}
		case rule.FieldComparator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comparator", values[i])
			} else if value.Valid {
				r.Comparator = value.String
			}
		case rule.FieldIsInversed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_inversed", values[i])
			} else if value.Valid {
				r.IsInversed = value.Bool
			}
		case rule.FieldConfigurations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field configurations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.Configurations); err != nil {
					return fmt.Errorf("unmarshal field configurations: %w", err)
				}
			}
		case rule.FieldWordlistID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field wordlist_id", values[i])
			} else if value.Valid {
				r.WordlistID = new(uuid.UUID)
				*r.WordlistID = *value.S.(*uuid.UUID)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rule.
// This includes values selected through modifiers, order, etc.
func (r *Rule) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryTarget queries the "target" edge of the Rule entity.
func (r *Rule) QueryTarget() *TargetQuery {
	return NewRuleClient(r.config).QueryTarget(r)
}

// QueryWordlist queries the "wordlist" edge of the Rule entity.
func (r *Rule) QueryWordlist() *WordlistQuery {
	return NewRuleClient(r.config).QueryWordlist(r)
}

// QueryActions queries the "actions" edge of the Rule entity.
func (r *Rule) QueryActions() *ActionQuery {
	return NewRuleClient(r.config).QueryActions(r)
}

// QueryPrinciples queries the "principles" edge of the Rule entity.
func (r *Rule) QueryPrinciples() *PrincipleQuery {
	return NewRuleClient(r.config).QueryPrinciples(r)
}

// Update returns a builder for updating this Rule.
// Note that you need to call Rule.Unwrap() before calling this method if this Rule
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Rule) Update() *RuleUpdateOne {
	return NewRuleClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Rule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Rule) Unwrap() *Rule {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rule is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Rule) String() string {
	var builder strings.Builder
	builder.WriteString("Rule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("name=")
	builder.WriteString(r.Name)
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", r.Phase))
	builder.WriteString(", ")
	if v := r.TargetID; v != nil {
		builder.WriteString("target_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("comparator=")
	builder.WriteString(r.Comparator)
	builder.WriteString(", ")
	builder.WriteString("is_inversed=")
	builder.WriteString(fmt.Sprintf("%v", r.IsInversed))
	builder.WriteString(", ")
	builder.WriteString("configurations=")
	builder.WriteString(fmt.Sprintf("%v", r.Configurations))
	builder.WriteString(", ")
	if v := r.WordlistID; v != nil {
		builder.WriteString("wordlist_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Rules is a parsable slice of Rule.
type Rules []*Rule
