// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/engine"
	"defly-defender/ent/pattern"
	"defly-defender/ent/rule"
	"defly-defender/ent/target"
	"defly-defender/ent/user"
	"defly-defender/ent/wordlist"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TargetCreate is the builder for creating a Target entity.
type TargetCreate struct {
	config
	mutation *TargetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TargetCreate) SetName(s string) *TargetCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetPhase sets the "phase" field.
func (tc *TargetCreate) SetPhase(i int) *TargetCreate {
	tc.mutation.SetPhase(i)
	return tc
}

// SetType sets the "type" field.
func (tc *TargetCreate) SetType(t target.Type) *TargetCreate {
	tc.mutation.SetType(t)
	return tc
}

// SetDatatype sets the "datatype" field.
func (tc *TargetCreate) SetDatatype(t target.Datatype) *TargetCreate {
	tc.mutation.SetDatatype(t)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TargetCreate) SetDescription(s string) *TargetCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *TargetCreate) SetNillableDescription(s *string) *TargetCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetPatternID sets the "pattern_id" field.
func (tc *TargetCreate) SetPatternID(u uuid.UUID) *TargetCreate {
	tc.mutation.SetPatternID(u)
	return tc
}

// SetNillablePatternID sets the "pattern_id" field if the given value is not nil.
func (tc *TargetCreate) SetNillablePatternID(u *uuid.UUID) *TargetCreate {
	if u != nil {
		tc.SetPatternID(*u)
	}
	return tc
}

// SetWordlistID sets the "wordlist_id" field.
func (tc *TargetCreate) SetWordlistID(u uuid.UUID) *TargetCreate {
	tc.mutation.SetWordlistID(u)
	return tc
}

// SetNillableWordlistID sets the "wordlist_id" field if the given value is not nil.
func (tc *TargetCreate) SetNillableWordlistID(u *uuid.UUID) *TargetCreate {
	if u != nil {
		tc.SetWordlistID(*u)
	}
	return tc
}

// SetCreatedBy sets the "created_by" field.
func (tc *TargetCreate) SetCreatedBy(u uuid.UUID) *TargetCreate {
	tc.mutation.SetCreatedBy(u)
	return tc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (tc *TargetCreate) SetNillableCreatedBy(u *uuid.UUID) *TargetCreate {
	if u != nil {
		tc.SetCreatedBy(*u)
	}
	return tc
}

// SetIsLocked sets the "is_locked" field.
func (tc *TargetCreate) SetIsLocked(b bool) *TargetCreate {
	tc.mutation.SetIsLocked(b)
	return tc
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (tc *TargetCreate) SetNillableIsLocked(b *bool) *TargetCreate {
	if b != nil {
		tc.SetIsLocked(*b)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TargetCreate) SetCreatedAt(t time.Time) *TargetCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TargetCreate) SetNillableCreatedAt(t *time.Time) *TargetCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TargetCreate) SetUpdatedAt(t time.Time) *TargetCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TargetCreate) SetNillableUpdatedAt(t *time.Time) *TargetCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TargetCreate) SetID(u uuid.UUID) *TargetCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TargetCreate) SetNillableID(u *uuid.UUID) *TargetCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// SetPattern sets the "pattern" edge to the Pattern entity.
func (tc *TargetCreate) SetPattern(p *Pattern) *TargetCreate {
	return tc.SetPatternID(p.ID)
}

// SetWordlist sets the "wordlist" edge to the Wordlist entity.
func (tc *TargetCreate) SetWordlist(w *Wordlist) *TargetCreate {
	return tc.SetWordlistID(w.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (tc *TargetCreate) SetCreatorID(id uuid.UUID) *TargetCreate {
	tc.mutation.SetCreatorID(id)
	return tc
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (tc *TargetCreate) SetNillableCreatorID(id *uuid.UUID) *TargetCreate {
	if id != nil {
		tc = tc.SetCreatorID(*id)
	}
	return tc
}

// SetCreator sets the "creator" edge to the User entity.
func (tc *TargetCreate) SetCreator(u *User) *TargetCreate {
	return tc.SetCreatorID(u.ID)
}

// AddEngineIDs adds the "engines" edge to the Engine entity by IDs.
func (tc *TargetCreate) AddEngineIDs(ids ...uuid.UUID) *TargetCreate {
	tc.mutation.AddEngineIDs(ids...)
	return tc
}

// AddEngines adds the "engines" edges to the Engine entity.
func (tc *TargetCreate) AddEngines(e ...*Engine) *TargetCreate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tc.AddEngineIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (tc *TargetCreate) AddRuleIDs(ids ...uuid.UUID) *TargetCreate {
	tc.mutation.AddRuleIDs(ids...)
	return tc
}

// AddRules adds the "rules" edges to the Rule entity.
func (tc *TargetCreate) AddRules(r ...*Rule) *TargetCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tc.AddRuleIDs(ids...)
}

// Mutation returns the TargetMutation object of the builder.
func (tc *TargetCreate) Mutation() *TargetMutation {
	return tc.mutation
}

// Save creates the Target in the database.
func (tc *TargetCreate) Save(ctx context.Context) (*Target, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TargetCreate) SaveX(ctx context.Context) *Target {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TargetCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TargetCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TargetCreate) defaults() {
	if _, ok := tc.mutation.IsLocked(); !ok {
		v := target.DefaultIsLocked
		tc.mutation.SetIsLocked(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := target.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := target.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := target.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TargetCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Target.name"`)}
	}
	if v, ok := tc.mutation.Name(); ok {
		if err := target.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Target.name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "Target.phase"`)}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Target.type"`)}
	}
	if v, ok := tc.mutation.GetType(); ok {
		if err := target.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Target.type": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Datatype(); !ok {
		return &ValidationError{Name: "datatype", err: errors.New(`ent: missing required field "Target.datatype"`)}
	}
	if v, ok := tc.mutation.Datatype(); ok {
		if err := target.DatatypeValidator(v); err != nil {
			return &ValidationError{Name: "datatype", err: fmt.Errorf(`ent: validator failed for field "Target.datatype": %w`, err)}
		}
	}
	if _, ok := tc.mutation.IsLocked(); !ok {
		return &ValidationError{Name: "is_locked", err: errors.New(`ent: missing required field "Target.is_locked"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Target.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Target.updated_at"`)}
	}
	return nil
}

func (tc *TargetCreate) sqlSave(ctx context.Context) (*Target, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TargetCreate) createSpec() (*Target, *sqlgraph.CreateSpec) {
	var (
		_node = &Target{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(target.Table, sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(target.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Phase(); ok {
		_spec.SetField(target.FieldPhase, field.TypeInt, value)
		_node.Phase = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(target.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.Datatype(); ok {
		_spec.SetField(target.FieldDatatype, field.TypeEnum, value)
		_node.Datatype = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(target.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := tc.mutation.IsLocked(); ok {
		_spec.SetField(target.FieldIsLocked, field.TypeBool, value)
		_node.IsLocked = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(target.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(target.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.PatternIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   target.PatternTable,
			Columns: []string{target.PatternColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pattern.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PatternID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.WordlistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   target.WordlistTable,
			Columns: []string{target.WordlistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WordlistID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   target.CreatorTable,
			Columns: []string{target.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.EnginesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   target.EnginesTable,
			Columns: target.EnginesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(engine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.RulesTable,
			Columns: []string{target.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TargetCreateBulk is the builder for creating many Target entities in bulk.
type TargetCreateBulk struct {
	config
	err      error
	builders []*TargetCreate
}

// Save creates the Target entities in the database.
func (tcb *TargetCreateBulk) Save(ctx context.Context) ([]*Target, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Target, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TargetCreateBulk) SaveX(ctx context.Context) []*Target {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TargetCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TargetCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
