// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"defly-defender/ent/predicate"
	"defly-defender/ent/rule"
	"defly-defender/ent/target"
	"defly-defender/ent/wordlist"
	"defly-defender/internal/types"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WordlistUpdate is the builder for updating Wordlist entities.
type WordlistUpdate struct {
	config
	hooks    []Hook
	mutation *WordlistMutation
}

// Where appends a list predicates to the WordlistUpdate builder.
func (wu *WordlistUpdate) Where(ps ...predicate.Wordlist) *WordlistUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WordlistUpdate) SetName(s string) *WordlistUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WordlistUpdate) SetNillableName(s *string) *WordlistUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetType sets the "type" field.
func (wu *WordlistUpdate) SetType(w wordlist.Type) *WordlistUpdate {
	wu.mutation.SetType(w)
	return wu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wu *WordlistUpdate) SetNillableType(w *wordlist.Type) *WordlistUpdate {
	if w != nil {
		wu.SetType(*w)
	}
	return wu
}

// SetWordFile sets the "word_file" field.
func (wu *WordlistUpdate) SetWordFile(s string) *WordlistUpdate {
	wu.mutation.SetWordFile(s)
	return wu
}

// SetNillableWordFile sets the "word_file" field if the given value is not nil.
func (wu *WordlistUpdate) SetNillableWordFile(s *string) *WordlistUpdate {
	if s != nil {
		wu.SetWordFile(*s)
	}
	return wu
}

// ClearWordFile clears the value of the "word_file" field.
func (wu *WordlistUpdate) ClearWordFile() *WordlistUpdate {
	wu.mutation.ClearWordFile()
	return wu
}

// SetWordJSON sets the "word_json" field.
func (wu *WordlistUpdate) SetWordJSON(ti []types.WordlistItem) *WordlistUpdate {
	wu.mutation.SetWordJSON(ti)
	return wu
}

// AppendWordJSON appends ti to the "word_json" field.
func (wu *WordlistUpdate) AppendWordJSON(ti []types.WordlistItem) *WordlistUpdate {
	wu.mutation.AppendWordJSON(ti)
	return wu
}

// ClearWordJSON clears the value of the "word_json" field.
func (wu *WordlistUpdate) ClearWordJSON() *WordlistUpdate {
	wu.mutation.ClearWordJSON()
	return wu
}

// SetWordCount sets the "word_count" field.
func (wu *WordlistUpdate) SetWordCount(i int) *WordlistUpdate {
	wu.mutation.ResetWordCount()
	wu.mutation.SetWordCount(i)
	return wu
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (wu *WordlistUpdate) SetNillableWordCount(i *int) *WordlistUpdate {
	if i != nil {
		wu.SetWordCount(*i)
	}
	return wu
}

// AddWordCount adds i to the "word_count" field.
func (wu *WordlistUpdate) AddWordCount(i int) *WordlistUpdate {
	wu.mutation.AddWordCount(i)
	return wu
}

// ClearWordCount clears the value of the "word_count" field.
func (wu *WordlistUpdate) ClearWordCount() *WordlistUpdate {
	wu.mutation.ClearWordCount()
	return wu
}

// AddTargetIDs adds the "targets" edge to the Target entity by IDs.
func (wu *WordlistUpdate) AddTargetIDs(ids ...uuid.UUID) *WordlistUpdate {
	wu.mutation.AddTargetIDs(ids...)
	return wu
}

// AddTargets adds the "targets" edges to the Target entity.
func (wu *WordlistUpdate) AddTargets(t ...*Target) *WordlistUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wu.AddTargetIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (wu *WordlistUpdate) AddRuleIDs(ids ...uuid.UUID) *WordlistUpdate {
	wu.mutation.AddRuleIDs(ids...)
	return wu
}

// AddRules adds the "rules" edges to the Rule entity.
func (wu *WordlistUpdate) AddRules(r ...*Rule) *WordlistUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return wu.AddRuleIDs(ids...)
}

// Mutation returns the WordlistMutation object of the builder.
func (wu *WordlistUpdate) Mutation() *WordlistMutation {
	return wu.mutation
}

// ClearTargets clears all "targets" edges to the Target entity.
func (wu *WordlistUpdate) ClearTargets() *WordlistUpdate {
	wu.mutation.ClearTargets()
	return wu
}

// RemoveTargetIDs removes the "targets" edge to Target entities by IDs.
func (wu *WordlistUpdate) RemoveTargetIDs(ids ...uuid.UUID) *WordlistUpdate {
	wu.mutation.RemoveTargetIDs(ids...)
	return wu
}

// RemoveTargets removes "targets" edges to Target entities.
func (wu *WordlistUpdate) RemoveTargets(t ...*Target) *WordlistUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wu.RemoveTargetIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (wu *WordlistUpdate) ClearRules() *WordlistUpdate {
	wu.mutation.ClearRules()
	return wu
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (wu *WordlistUpdate) RemoveRuleIDs(ids ...uuid.UUID) *WordlistUpdate {
	wu.mutation.RemoveRuleIDs(ids...)
	return wu
}

// RemoveRules removes "rules" edges to Rule entities.
func (wu *WordlistUpdate) RemoveRules(r ...*Rule) *WordlistUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return wu.RemoveRuleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WordlistUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WordlistUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WordlistUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WordlistUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WordlistUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := wordlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Wordlist.name": %w`, err)}
		}
	}
	if v, ok := wu.mutation.GetType(); ok {
		if err := wordlist.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Wordlist.type": %w`, err)}
		}
	}
	return nil
}

func (wu *WordlistUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(wordlist.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.GetType(); ok {
		_spec.SetField(wordlist.FieldType, field.TypeEnum, value)
	}
	if value, ok := wu.mutation.WordFile(); ok {
		_spec.SetField(wordlist.FieldWordFile, field.TypeString, value)
	}
	if wu.mutation.WordFileCleared() {
		_spec.ClearField(wordlist.FieldWordFile, field.TypeString)
	}
	if value, ok := wu.mutation.WordJSON(); ok {
		_spec.SetField(wordlist.FieldWordJSON, field.TypeJSON, value)
	}
	if value, ok := wu.mutation.AppendedWordJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, wordlist.FieldWordJSON, value)
		})
	}
	if wu.mutation.WordJSONCleared() {
		_spec.ClearField(wordlist.FieldWordJSON, field.TypeJSON)
	}
	if value, ok := wu.mutation.WordCount(); ok {
		_spec.SetField(wordlist.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedWordCount(); ok {
		_spec.AddField(wordlist.FieldWordCount, field.TypeInt, value)
	}
	if wu.mutation.WordCountCleared() {
		_spec.ClearField(wordlist.FieldWordCount, field.TypeInt)
	}
	if wu.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !wu.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedRulesIDs(); len(nodes) > 0 && !wu.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wordlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WordlistUpdateOne is the builder for updating a single Wordlist entity.
type WordlistUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WordlistMutation
}

// SetName sets the "name" field.
func (wuo *WordlistUpdateOne) SetName(s string) *WordlistUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WordlistUpdateOne) SetNillableName(s *string) *WordlistUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetType sets the "type" field.
func (wuo *WordlistUpdateOne) SetType(w wordlist.Type) *WordlistUpdateOne {
	wuo.mutation.SetType(w)
	return wuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wuo *WordlistUpdateOne) SetNillableType(w *wordlist.Type) *WordlistUpdateOne {
	if w != nil {
		wuo.SetType(*w)
	}
	return wuo
}

// SetWordFile sets the "word_file" field.
func (wuo *WordlistUpdateOne) SetWordFile(s string) *WordlistUpdateOne {
	wuo.mutation.SetWordFile(s)
	return wuo
}

// SetNillableWordFile sets the "word_file" field if the given value is not nil.
func (wuo *WordlistUpdateOne) SetNillableWordFile(s *string) *WordlistUpdateOne {
	if s != nil {
		wuo.SetWordFile(*s)
	}
	return wuo
}

// ClearWordFile clears the value of the "word_file" field.
func (wuo *WordlistUpdateOne) ClearWordFile() *WordlistUpdateOne {
	wuo.mutation.ClearWordFile()
	return wuo
}

// SetWordJSON sets the "word_json" field.
func (wuo *WordlistUpdateOne) SetWordJSON(ti []types.WordlistItem) *WordlistUpdateOne {
	wuo.mutation.SetWordJSON(ti)
	return wuo
}

// AppendWordJSON appends ti to the "word_json" field.
func (wuo *WordlistUpdateOne) AppendWordJSON(ti []types.WordlistItem) *WordlistUpdateOne {
	wuo.mutation.AppendWordJSON(ti)
	return wuo
}

// ClearWordJSON clears the value of the "word_json" field.
func (wuo *WordlistUpdateOne) ClearWordJSON() *WordlistUpdateOne {
	wuo.mutation.ClearWordJSON()
	return wuo
}

// SetWordCount sets the "word_count" field.
func (wuo *WordlistUpdateOne) SetWordCount(i int) *WordlistUpdateOne {
	wuo.mutation.ResetWordCount()
	wuo.mutation.SetWordCount(i)
	return wuo
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (wuo *WordlistUpdateOne) SetNillableWordCount(i *int) *WordlistUpdateOne {
	if i != nil {
		wuo.SetWordCount(*i)
	}
	return wuo
}

// AddWordCount adds i to the "word_count" field.
func (wuo *WordlistUpdateOne) AddWordCount(i int) *WordlistUpdateOne {
	wuo.mutation.AddWordCount(i)
	return wuo
}

// ClearWordCount clears the value of the "word_count" field.
func (wuo *WordlistUpdateOne) ClearWordCount() *WordlistUpdateOne {
	wuo.mutation.ClearWordCount()
	return wuo
}

// AddTargetIDs adds the "targets" edge to the Target entity by IDs.
func (wuo *WordlistUpdateOne) AddTargetIDs(ids ...uuid.UUID) *WordlistUpdateOne {
	wuo.mutation.AddTargetIDs(ids...)
	return wuo
}

// AddTargets adds the "targets" edges to the Target entity.
func (wuo *WordlistUpdateOne) AddTargets(t ...*Target) *WordlistUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wuo.AddTargetIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (wuo *WordlistUpdateOne) AddRuleIDs(ids ...uuid.UUID) *WordlistUpdateOne {
	wuo.mutation.AddRuleIDs(ids...)
	return wuo
}

// AddRules adds the "rules" edges to the Rule entity.
func (wuo *WordlistUpdateOne) AddRules(r ...*Rule) *WordlistUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return wuo.AddRuleIDs(ids...)
}

// Mutation returns the WordlistMutation object of the builder.
func (wuo *WordlistUpdateOne) Mutation() *WordlistMutation {
	return wuo.mutation
}

// ClearTargets clears all "targets" edges to the Target entity.
func (wuo *WordlistUpdateOne) ClearTargets() *WordlistUpdateOne {
	wuo.mutation.ClearTargets()
	return wuo
}

// RemoveTargetIDs removes the "targets" edge to Target entities by IDs.
func (wuo *WordlistUpdateOne) RemoveTargetIDs(ids ...uuid.UUID) *WordlistUpdateOne {
	wuo.mutation.RemoveTargetIDs(ids...)
	return wuo
}

// RemoveTargets removes "targets" edges to Target entities.
func (wuo *WordlistUpdateOne) RemoveTargets(t ...*Target) *WordlistUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wuo.RemoveTargetIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (wuo *WordlistUpdateOne) ClearRules() *WordlistUpdateOne {
	wuo.mutation.ClearRules()
	return wuo
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (wuo *WordlistUpdateOne) RemoveRuleIDs(ids ...uuid.UUID) *WordlistUpdateOne {
	wuo.mutation.RemoveRuleIDs(ids...)
	return wuo
}

// RemoveRules removes "rules" edges to Rule entities.
func (wuo *WordlistUpdateOne) RemoveRules(r ...*Rule) *WordlistUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return wuo.RemoveRuleIDs(ids...)
}

// Where appends a list predicates to the WordlistUpdate builder.
func (wuo *WordlistUpdateOne) Where(ps ...predicate.Wordlist) *WordlistUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WordlistUpdateOne) Select(field string, fields ...string) *WordlistUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Wordlist entity.
func (wuo *WordlistUpdateOne) Save(ctx context.Context) (*Wordlist, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WordlistUpdateOne) SaveX(ctx context.Context) *Wordlist {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WordlistUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WordlistUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WordlistUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := wordlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Wordlist.name": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.GetType(); ok {
		if err := wordlist.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Wordlist.type": %w`, err)}
		}
	}
	return nil
}

func (wuo *WordlistUpdateOne) sqlSave(ctx context.Context) (_node *Wordlist, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wordlist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordlist.FieldID)
		for _, f := range fields {
			if !wordlist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wordlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(wordlist.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.GetType(); ok {
		_spec.SetField(wordlist.FieldType, field.TypeEnum, value)
	}
	if value, ok := wuo.mutation.WordFile(); ok {
		_spec.SetField(wordlist.FieldWordFile, field.TypeString, value)
	}
	if wuo.mutation.WordFileCleared() {
		_spec.ClearField(wordlist.FieldWordFile, field.TypeString)
	}
	if value, ok := wuo.mutation.WordJSON(); ok {
		_spec.SetField(wordlist.FieldWordJSON, field.TypeJSON, value)
	}
	if value, ok := wuo.mutation.AppendedWordJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, wordlist.FieldWordJSON, value)
		})
	}
	if wuo.mutation.WordJSONCleared() {
		_spec.ClearField(wordlist.FieldWordJSON, field.TypeJSON)
	}
	if value, ok := wuo.mutation.WordCount(); ok {
		_spec.SetField(wordlist.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedWordCount(); ok {
		_spec.AddField(wordlist.FieldWordCount, field.TypeInt, value)
	}
	if wuo.mutation.WordCountCleared() {
		_spec.ClearField(wordlist.FieldWordCount, field.TypeInt)
	}
	if wuo.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !wuo.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.TargetsTable,
			Columns: []string{wordlist.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedRulesIDs(); len(nodes) > 0 && !wuo.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wordlist.RulesTable,
			Columns: []string{wordlist.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Wordlist{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wordlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
