// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"defly-defender/ent/predicate"
	"defly-defender/ent/rule"
	"defly-defender/ent/target"
	"defly-defender/ent/wordlist"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WordlistQuery is the builder for querying Wordlist entities.
type WordlistQuery struct {
	config
	ctx         *QueryContext
	order       []wordlist.OrderOption
	inters      []Interceptor
	predicates  []predicate.Wordlist
	withTargets *TargetQuery
	withRules   *RuleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WordlistQuery builder.
func (wq *WordlistQuery) Where(ps ...predicate.Wordlist) *WordlistQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WordlistQuery) Limit(limit int) *WordlistQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WordlistQuery) Offset(offset int) *WordlistQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WordlistQuery) Unique(unique bool) *WordlistQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WordlistQuery) Order(o ...wordlist.OrderOption) *WordlistQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryTargets chains the current query on the "targets" edge.
func (wq *WordlistQuery) QueryTargets() *TargetQuery {
	query := (&TargetClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wordlist.TargetsTable, wordlist.TargetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRules chains the current query on the "rules" edge.
func (wq *WordlistQuery) QueryRules() *RuleQuery {
	query := (&RuleClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(rule.Table, rule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wordlist.RulesTable, wordlist.RulesColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Wordlist entity from the query.
// Returns a *NotFoundError when no Wordlist was found.
func (wq *WordlistQuery) First(ctx context.Context) (*Wordlist, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wordlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WordlistQuery) FirstX(ctx context.Context) *Wordlist {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Wordlist ID from the query.
// Returns a *NotFoundError when no Wordlist ID was found.
func (wq *WordlistQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wordlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WordlistQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Wordlist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Wordlist entity is found.
// Returns a *NotFoundError when no Wordlist entities are found.
func (wq *WordlistQuery) Only(ctx context.Context) (*Wordlist, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wordlist.Label}
	default:
		return nil, &NotSingularError{wordlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WordlistQuery) OnlyX(ctx context.Context) *Wordlist {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Wordlist ID in the query.
// Returns a *NotSingularError when more than one Wordlist ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WordlistQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wordlist.Label}
	default:
		err = &NotSingularError{wordlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WordlistQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Wordlists.
func (wq *WordlistQuery) All(ctx context.Context) ([]*Wordlist, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryAll)
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Wordlist, *WordlistQuery]()
	return withInterceptors[[]*Wordlist](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WordlistQuery) AllX(ctx context.Context) []*Wordlist {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Wordlist IDs.
func (wq *WordlistQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryIDs)
	if err = wq.Select(wordlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WordlistQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WordlistQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryCount)
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WordlistQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WordlistQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WordlistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryExist)
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WordlistQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WordlistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WordlistQuery) Clone() *WordlistQuery {
	if wq == nil {
		return nil
	}
	return &WordlistQuery{
		config:      wq.config,
		ctx:         wq.ctx.Clone(),
		order:       append([]wordlist.OrderOption{}, wq.order...),
		inters:      append([]Interceptor{}, wq.inters...),
		predicates:  append([]predicate.Wordlist{}, wq.predicates...),
		withTargets: wq.withTargets.Clone(),
		withRules:   wq.withRules.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithTargets tells the query-builder to eager-load the nodes that are connected to
// the "targets" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WordlistQuery) WithTargets(opts ...func(*TargetQuery)) *WordlistQuery {
	query := (&TargetClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withTargets = query
	return wq
}

// WithRules tells the query-builder to eager-load the nodes that are connected to
// the "rules" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WordlistQuery) WithRules(opts ...func(*RuleQuery)) *WordlistQuery {
	query := (&RuleClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withRules = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Wordlist.Query().
//		GroupBy(wordlist.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WordlistQuery) GroupBy(field string, fields ...string) *WordlistGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WordlistGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = wordlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Wordlist.Query().
//		Select(wordlist.FieldName).
//		Scan(ctx, &v)
func (wq *WordlistQuery) Select(fields ...string) *WordlistSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WordlistSelect{WordlistQuery: wq}
	sbuild.label = wordlist.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WordlistSelect configured with the given aggregations.
func (wq *WordlistQuery) Aggregate(fns ...AggregateFunc) *WordlistSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WordlistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !wordlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WordlistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Wordlist, error) {
	var (
		nodes       = []*Wordlist{}
		_spec       = wq.querySpec()
		loadedTypes = [2]bool{
			wq.withTargets != nil,
			wq.withRules != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Wordlist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Wordlist{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withTargets; query != nil {
		if err := wq.loadTargets(ctx, query, nodes,
			func(n *Wordlist) { n.Edges.Targets = []*Target{} },
			func(n *Wordlist, e *Target) { n.Edges.Targets = append(n.Edges.Targets, e) }); err != nil {
			return nil, err
		}
	}
	if query := wq.withRules; query != nil {
		if err := wq.loadRules(ctx, query, nodes,
			func(n *Wordlist) { n.Edges.Rules = []*Rule{} },
			func(n *Wordlist, e *Rule) { n.Edges.Rules = append(n.Edges.Rules, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WordlistQuery) loadTargets(ctx context.Context, query *TargetQuery, nodes []*Wordlist, init func(*Wordlist), assign func(*Wordlist, *Target)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Wordlist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(target.FieldWordlistID)
	}
	query.Where(predicate.Target(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wordlist.TargetsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WordlistID
		if fk == nil {
			return fmt.Errorf(`foreign-key "wordlist_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wordlist_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WordlistQuery) loadRules(ctx context.Context, query *RuleQuery, nodes []*Wordlist, init func(*Wordlist), assign func(*Wordlist, *Rule)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Wordlist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rule.FieldWordlistID)
	}
	query.Where(predicate.Rule(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wordlist.RulesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WordlistID
		if fk == nil {
			return fmt.Errorf(`foreign-key "wordlist_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wordlist_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wq *WordlistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WordlistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeUUID))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordlist.FieldID)
		for i := range fields {
			if fields[i] != wordlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WordlistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(wordlist.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = wordlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WordlistGroupBy is the group-by builder for Wordlist entities.
type WordlistGroupBy struct {
	selector
	build *WordlistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WordlistGroupBy) Aggregate(fns ...AggregateFunc) *WordlistGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WordlistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, ent.OpQueryGroupBy)
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordlistQuery, *WordlistGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WordlistGroupBy) sqlScan(ctx context.Context, root *WordlistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WordlistSelect is the builder for selecting fields of Wordlist entities.
type WordlistSelect struct {
	*WordlistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WordlistSelect) Aggregate(fns ...AggregateFunc) *WordlistSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WordlistSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, ent.OpQuerySelect)
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordlistQuery, *WordlistSelect](ctx, ws.WordlistQuery, ws, ws.inters, v)
}

func (ws *WordlistSelect) sqlScan(ctx context.Context, root *WordlistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
