// Code generated by ent, DO NOT EDIT.

package ent

import (
	"defly-defender/ent/user"
	"defly-defender/ent/wordlist"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Wordlist is the model entity for the Wordlist schema.
type Wordlist struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type wordlist.Type `json:"type,omitempty"`
	// WordFile holds the value of the "word_file" field.
	WordFile *string `json:"word_file,omitempty"`
	// WordJSON holds the value of the "word_json" field.
	WordJSON []string `json:"word_json,omitempty"`
	// WordCount holds the value of the "word_count" field.
	WordCount *int `json:"word_count,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// IsLocked holds the value of the "is_locked" field.
	IsLocked bool `json:"is_locked,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WordlistQuery when eager-loading is set.
	Edges        WordlistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WordlistEdges holds the relations/edges for other nodes in the graph.
type WordlistEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Targets holds the value of the targets edge.
	Targets []*Target `json:"targets,omitempty"`
	// Rules holds the value of the rules edge.
	Rules []*Rule `json:"rules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WordlistEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// TargetsOrErr returns the Targets value or an error if the edge
// was not loaded in eager-loading.
func (e WordlistEdges) TargetsOrErr() ([]*Target, error) {
	if e.loadedTypes[1] {
		return e.Targets, nil
	}
	return nil, &NotLoadedError{edge: "targets"}
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e WordlistEdges) RulesOrErr() ([]*Rule, error) {
	if e.loadedTypes[2] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wordlist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wordlist.FieldCreatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case wordlist.FieldWordJSON:
			values[i] = new([]byte)
		case wordlist.FieldIsLocked:
			values[i] = new(sql.NullBool)
		case wordlist.FieldWordCount:
			values[i] = new(sql.NullInt64)
		case wordlist.FieldName, wordlist.FieldType, wordlist.FieldWordFile, wordlist.FieldDescription:
			values[i] = new(sql.NullString)
		case wordlist.FieldCreatedAt, wordlist.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case wordlist.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wordlist fields.
func (w *Wordlist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wordlist.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				w.ID = *value
			}
		case wordlist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				w.Name = value.String
			}
		case wordlist.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				w.Type = wordlist.Type(value.String)
			}
		case wordlist.FieldWordFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field word_file", values[i])
			} else if value.Valid {
				w.WordFile = new(string)
				*w.WordFile = value.String
			}
		case wordlist.FieldWordJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field word_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &w.WordJSON); err != nil {
					return fmt.Errorf("unmarshal field word_json: %w", err)
				}
			}
		case wordlist.FieldWordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field word_count", values[i])
			} else if value.Valid {
				w.WordCount = new(int)
				*w.WordCount = int(value.Int64)
			}
		case wordlist.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				w.Description = new(string)
				*w.Description = value.String
			}
		case wordlist.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				w.CreatedBy = new(uuid.UUID)
				*w.CreatedBy = *value.S.(*uuid.UUID)
			}
		case wordlist.FieldIsLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_locked", values[i])
			} else if value.Valid {
				w.IsLocked = value.Bool
			}
		case wordlist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				w.CreatedAt = value.Time
			}
		case wordlist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				w.UpdatedAt = value.Time
			}
		default:
			w.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Wordlist.
// This includes values selected through modifiers, order, etc.
func (w *Wordlist) Value(name string) (ent.Value, error) {
	return w.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Wordlist entity.
func (w *Wordlist) QueryCreator() *UserQuery {
	return NewWordlistClient(w.config).QueryCreator(w)
}

// QueryTargets queries the "targets" edge of the Wordlist entity.
func (w *Wordlist) QueryTargets() *TargetQuery {
	return NewWordlistClient(w.config).QueryTargets(w)
}

// QueryRules queries the "rules" edge of the Wordlist entity.
func (w *Wordlist) QueryRules() *RuleQuery {
	return NewWordlistClient(w.config).QueryRules(w)
}

// Update returns a builder for updating this Wordlist.
// Note that you need to call Wordlist.Unwrap() before calling this method if this Wordlist
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Wordlist) Update() *WordlistUpdateOne {
	return NewWordlistClient(w.config).UpdateOne(w)
}

// Unwrap unwraps the Wordlist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Wordlist) Unwrap() *Wordlist {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wordlist is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Wordlist) String() string {
	var builder strings.Builder
	builder.WriteString("Wordlist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("name=")
	builder.WriteString(w.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", w.Type))
	builder.WriteString(", ")
	if v := w.WordFile; v != nil {
		builder.WriteString("word_file=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("word_json=")
	builder.WriteString(fmt.Sprintf("%v", w.WordJSON))
	builder.WriteString(", ")
	if v := w.WordCount; v != nil {
		builder.WriteString("word_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := w.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := w.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_locked=")
	builder.WriteString(fmt.Sprintf("%v", w.IsLocked))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(w.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(w.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Wordlists is a parsable slice of Wordlist.
type Wordlists []*Wordlist
