// Code generated by ent, DO NOT EDIT.

package engine

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the engine type in the database.
	Label = "engine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldInputDatatype holds the string denoting the input_datatype field in the database.
	FieldInputDatatype = "input_datatype"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldConfigurations holds the string denoting the configurations field in the database.
	FieldConfigurations = "configurations"
	// FieldOutputDatatype holds the string denoting the output_datatype field in the database.
	FieldOutputDatatype = "output_datatype"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldIsLocked holds the string denoting the is_locked field in the database.
	FieldIsLocked = "is_locked"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeTargets holds the string denoting the targets edge name in mutations.
	EdgeTargets = "targets"
	// Table holds the table name of the engine in the database.
	Table = "engines"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "engines"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// TargetsTable is the table that holds the targets relation/edge. The primary key declared below.
	TargetsTable = "targets_engines"
	// TargetsInverseTable is the table name for the Target entity.
	// It exists in this package in order to avoid circular dependency with the "target" package.
	TargetsInverseTable = "targets"
)

// Columns holds all SQL columns for engine fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldInputDatatype,
	FieldType,
	FieldConfigurations,
	FieldOutputDatatype,
	FieldDescription,
	FieldCreatedBy,
	FieldIsLocked,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TargetsPrimaryKey and TargetsColumn2 are the table columns denoting the
	// primary key for the targets relation (M2M).
	TargetsPrimaryKey = []string{"engine", "target"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultIsLocked holds the default value on creation for the "is_locked" field.
	DefaultIsLocked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// InputDatatype defines the type for the "input_datatype" enum field.
type InputDatatype string

// InputDatatype values.
const (
	InputDatatypeArray  InputDatatype = "array"
	InputDatatypeNumber InputDatatype = "number"
	InputDatatypeString InputDatatype = "string"
)

func (id InputDatatype) String() string {
	return string(id)
}

// InputDatatypeValidator is a validator for the "input_datatype" field enum values. It is called by the builders before save.
func InputDatatypeValidator(id InputDatatype) error {
	switch id {
	case InputDatatypeArray, InputDatatypeNumber, InputDatatypeString:
		return nil
	default:
		return fmt.Errorf("engine: invalid enum value for input_datatype field: %q", id)
	}
}

// OutputDatatype defines the type for the "output_datatype" enum field.
type OutputDatatype string

// OutputDatatype values.
const (
	OutputDatatypeArray  OutputDatatype = "array"
	OutputDatatypeNumber OutputDatatype = "number"
	OutputDatatypeString OutputDatatype = "string"
)

func (od OutputDatatype) String() string {
	return string(od)
}

// OutputDatatypeValidator is a validator for the "output_datatype" field enum values. It is called by the builders before save.
func OutputDatatypeValidator(od OutputDatatype) error {
	switch od {
	case OutputDatatypeArray, OutputDatatypeNumber, OutputDatatypeString:
		return nil
	default:
		return fmt.Errorf("engine: invalid enum value for output_datatype field: %q", od)
	}
}

// OrderOption defines the ordering options for the Engine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByInputDatatype orders the results by the input_datatype field.
func ByInputDatatype(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputDatatype, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByOutputDatatype orders the results by the output_datatype field.
func ByOutputDatatype(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputDatatype, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByIsLocked orders the results by the is_locked field.
func ByIsLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocked, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetsCount orders the results by targets count.
func ByTargetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTargetsStep(), opts...)
	}
}

// ByTargets orders the results by targets terms.
func ByTargets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newTargetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TargetsTable, TargetsPrimaryKey...),
	)
}
