// Code generated by ent, DO NOT EDIT.

package engine

import (
	"defly-defender/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Engine {
	return predicate.Engine(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Engine {
	return predicate.Engine(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Engine {
	return predicate.Engine(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Engine {
	return predicate.Engine(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Engine {
	return predicate.Engine(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Engine {
	return predicate.Engine(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Engine {
	return predicate.Engine(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Engine {
	return predicate.Engine(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Engine {
	return predicate.Engine(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Engine {
	return predicate.Engine(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Engine {
	return predicate.Engine(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Engine {
	return predicate.Engine(sql.FieldContainsFold(FieldName, v))
}

// InputDatatypeEQ applies the EQ predicate on the "input_datatype" field.
func InputDatatypeEQ(v InputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldInputDatatype, v))
}

// InputDatatypeNEQ applies the NEQ predicate on the "input_datatype" field.
func InputDatatypeNEQ(v InputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldNEQ(FieldInputDatatype, v))
}

// InputDatatypeIn applies the In predicate on the "input_datatype" field.
func InputDatatypeIn(vs ...InputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldIn(FieldInputDatatype, vs...))
}

// InputDatatypeNotIn applies the NotIn predicate on the "input_datatype" field.
func InputDatatypeNotIn(vs ...InputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldNotIn(FieldInputDatatype, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Engine {
	return predicate.Engine(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Engine {
	return predicate.Engine(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Engine {
	return predicate.Engine(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Engine {
	return predicate.Engine(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Engine {
	return predicate.Engine(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Engine {
	return predicate.Engine(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Engine {
	return predicate.Engine(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Engine {
	return predicate.Engine(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Engine {
	return predicate.Engine(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Engine {
	return predicate.Engine(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Engine {
	return predicate.Engine(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Engine {
	return predicate.Engine(sql.FieldContainsFold(FieldType, v))
}

// ConfigurationsIsNil applies the IsNil predicate on the "configurations" field.
func ConfigurationsIsNil() predicate.Engine {
	return predicate.Engine(sql.FieldIsNull(FieldConfigurations))
}

// ConfigurationsNotNil applies the NotNil predicate on the "configurations" field.
func ConfigurationsNotNil() predicate.Engine {
	return predicate.Engine(sql.FieldNotNull(FieldConfigurations))
}

// OutputDatatypeEQ applies the EQ predicate on the "output_datatype" field.
func OutputDatatypeEQ(v OutputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldEQ(FieldOutputDatatype, v))
}

// OutputDatatypeNEQ applies the NEQ predicate on the "output_datatype" field.
func OutputDatatypeNEQ(v OutputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldNEQ(FieldOutputDatatype, v))
}

// OutputDatatypeIn applies the In predicate on the "output_datatype" field.
func OutputDatatypeIn(vs ...OutputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldIn(FieldOutputDatatype, vs...))
}

// OutputDatatypeNotIn applies the NotIn predicate on the "output_datatype" field.
func OutputDatatypeNotIn(vs ...OutputDatatype) predicate.Engine {
	return predicate.Engine(sql.FieldNotIn(FieldOutputDatatype, vs...))
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.Engine {
	return predicate.Engine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TargetsTable, TargetsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.Target) predicate.Engine {
	return predicate.Engine(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Engine) predicate.Engine {
	return predicate.Engine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Engine) predicate.Engine {
	return predicate.Engine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Engine) predicate.Engine {
	return predicate.Engine(sql.NotPredicates(p))
}
