// Code generated by ent, DO NOT EDIT.

package principle

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the principle type in the database.
	Label = "principle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldValidationStatus holds the string denoting the validation_status field in the database.
	FieldValidationStatus = "validation_status"
	// FieldValidationDetails holds the string denoting the validation_details field in the database.
	FieldValidationDetails = "validation_details"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldIsLocked holds the string denoting the is_locked field in the database.
	FieldIsLocked = "is_locked"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeRules holds the string denoting the rules edge name in mutations.
	EdgeRules = "rules"
	// EdgeDefenders holds the string denoting the defenders edge name in mutations.
	EdgeDefenders = "defenders"
	// Table holds the table name of the principle in the database.
	Table = "principles"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "principles"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// RulesTable is the table that holds the rules relation/edge. The primary key declared below.
	RulesTable = "principles_rules"
	// RulesInverseTable is the table name for the Rule entity.
	// It exists in this package in order to avoid circular dependency with the "rule" package.
	RulesInverseTable = "rules"
	// DefendersTable is the table that holds the defenders relation/edge. The primary key declared below.
	DefendersTable = "defenders_principles"
	// DefendersInverseTable is the table name for the Defender entity.
	// It exists in this package in order to avoid circular dependency with the "defender" package.
	DefendersInverseTable = "defenders"
)

// Columns holds all SQL columns for principle fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLevel,
	FieldPhase,
	FieldValidationStatus,
	FieldValidationDetails,
	FieldDescription,
	FieldCreatedBy,
	FieldIsLocked,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// RulesPrimaryKey and RulesColumn2 are the table columns denoting the
	// primary key for the rules relation (M2M).
	RulesPrimaryKey = []string{"rule", "principle"}
	// DefendersPrimaryKey and DefendersColumn2 are the table columns denoting the
	// primary key for the defenders relation (M2M).
	DefendersPrimaryKey = []string{"defender", "principle"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel uint64
	// DefaultIsLocked holds the default value on creation for the "is_locked" field.
	DefaultIsLocked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ValidationStatus defines the type for the "validation_status" enum field.
type ValidationStatus string

// ValidationStatus values.
const (
	ValidationStatusPending    ValidationStatus = "pending"
	ValidationStatusValidating ValidationStatus = "validating"
	ValidationStatusFailed     ValidationStatus = "failed"
	ValidationStatusPassed     ValidationStatus = "passed"
)

func (vs ValidationStatus) String() string {
	return string(vs)
}

// ValidationStatusValidator is a validator for the "validation_status" field enum values. It is called by the builders before save.
func ValidationStatusValidator(vs ValidationStatus) error {
	switch vs {
	case ValidationStatusPending, ValidationStatusValidating, ValidationStatusFailed, ValidationStatusPassed:
		return nil
	default:
		return fmt.Errorf("principle: invalid enum value for validation_status field: %q", vs)
	}
}

// OrderOption defines the ordering options for the Principle queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByValidationStatus orders the results by the validation_status field.
func ByValidationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidationStatus, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByIsLocked orders the results by the is_locked field.
func ByIsLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocked, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByRulesCount orders the results by rules count.
func ByRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRulesStep(), opts...)
	}
}

// ByRules orders the results by rules terms.
func ByRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDefendersCount orders the results by defenders count.
func ByDefendersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDefendersStep(), opts...)
	}
}

// ByDefenders orders the results by defenders terms.
func ByDefenders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDefendersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, RulesTable, RulesPrimaryKey...),
	)
}
func newDefendersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DefendersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, DefendersTable, DefendersPrimaryKey...),
	)
}
