// Code generated by ent, DO NOT EDIT.

package rule

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the rule type in the database.
	Label = "rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldComparator holds the string denoting the comparator field in the database.
	FieldComparator = "comparator"
	// FieldIsInversed holds the string denoting the is_inversed field in the database.
	FieldIsInversed = "is_inversed"
	// FieldConfigurations holds the string denoting the configurations field in the database.
	FieldConfigurations = "configurations"
	// FieldWordlistID holds the string denoting the wordlist_id field in the database.
	FieldWordlistID = "wordlist_id"
	// EdgeTarget holds the string denoting the target edge name in mutations.
	EdgeTarget = "target"
	// EdgeWordlist holds the string denoting the wordlist edge name in mutations.
	EdgeWordlist = "wordlist"
	// EdgeActions holds the string denoting the actions edge name in mutations.
	EdgeActions = "actions"
	// EdgePrinciples holds the string denoting the principles edge name in mutations.
	EdgePrinciples = "principles"
	// Table holds the table name of the rule in the database.
	Table = "rules"
	// TargetTable is the table that holds the target relation/edge.
	TargetTable = "rules"
	// TargetInverseTable is the table name for the Target entity.
	// It exists in this package in order to avoid circular dependency with the "target" package.
	TargetInverseTable = "targets"
	// TargetColumn is the table column denoting the target relation/edge.
	TargetColumn = "target_id"
	// WordlistTable is the table that holds the wordlist relation/edge.
	WordlistTable = "rules"
	// WordlistInverseTable is the table name for the Wordlist entity.
	// It exists in this package in order to avoid circular dependency with the "wordlist" package.
	WordlistInverseTable = "wordlists"
	// WordlistColumn is the table column denoting the wordlist relation/edge.
	WordlistColumn = "wordlist_id"
	// ActionsTable is the table that holds the actions relation/edge. The primary key declared below.
	ActionsTable = "rules_actions"
	// ActionsInverseTable is the table name for the Action entity.
	// It exists in this package in order to avoid circular dependency with the "action" package.
	ActionsInverseTable = "actions"
	// PrinciplesTable is the table that holds the principles relation/edge. The primary key declared below.
	PrinciplesTable = "principles_rules"
	// PrinciplesInverseTable is the table name for the Principle entity.
	// It exists in this package in order to avoid circular dependency with the "principle" package.
	PrinciplesInverseTable = "principles"
)

// Columns holds all SQL columns for rule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhase,
	FieldTargetID,
	FieldComparator,
	FieldIsInversed,
	FieldConfigurations,
	FieldWordlistID,
}

var (
	// ActionsPrimaryKey and ActionsColumn2 are the table columns denoting the
	// primary key for the actions relation (M2M).
	ActionsPrimaryKey = []string{"action", "rule"}
	// PrinciplesPrimaryKey and PrinciplesColumn2 are the table columns denoting the
	// primary key for the principles relation (M2M).
	PrinciplesPrimaryKey = []string{"rule", "principle"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ComparatorValidator is a validator for the "comparator" field. It is called by the builders before save.
	ComparatorValidator func(string) error
	// DefaultIsInversed holds the default value on creation for the "is_inversed" field.
	DefaultIsInversed bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Rule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByComparator orders the results by the comparator field.
func ByComparator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComparator, opts...).ToFunc()
}

// ByIsInversed orders the results by the is_inversed field.
func ByIsInversed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsInversed, opts...).ToFunc()
}

// ByWordlistID orders the results by the wordlist_id field.
func ByWordlistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWordlistID, opts...).ToFunc()
}

// ByTargetField orders the results by target field.
func ByTargetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetStep(), sql.OrderByField(field, opts...))
	}
}

// ByWordlistField orders the results by wordlist field.
func ByWordlistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWordlistStep(), sql.OrderByField(field, opts...))
	}
}

// ByActionsCount orders the results by actions count.
func ByActionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newActionsStep(), opts...)
	}
}

// ByActions orders the results by actions terms.
func ByActions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrinciplesCount orders the results by principles count.
func ByPrinciplesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrinciplesStep(), opts...)
	}
}

// ByPrinciples orders the results by principles terms.
func ByPrinciples(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrinciplesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
	)
}
func newWordlistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WordlistInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WordlistTable, WordlistColumn),
	)
}
func newActionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ActionsTable, ActionsPrimaryKey...),
	)
}
func newPrinciplesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrinciplesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PrinciplesTable, PrinciplesPrimaryKey...),
	)
}
