// Code generated by ent, DO NOT EDIT.

package wordlist

import (
	"defly-defender/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldName, v))
}

// WordFile applies equality check predicate on the "word_file" field. It's identical to WordFileEQ.
func WordFile(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldWordFile, v))
}

// WordCount applies equality check predicate on the "word_count" field. It's identical to WordCountEQ.
func WordCount(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldWordCount, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldDescription, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldCreatedBy, v))
}

// IsLocked applies equality check predicate on the "is_locked" field. It's identical to IsLockedEQ.
func IsLocked(v bool) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldIsLocked, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldType, vs...))
}

// WordFileEQ applies the EQ predicate on the "word_file" field.
func WordFileEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldWordFile, v))
}

// WordFileNEQ applies the NEQ predicate on the "word_file" field.
func WordFileNEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldWordFile, v))
}

// WordFileIn applies the In predicate on the "word_file" field.
func WordFileIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldWordFile, vs...))
}

// WordFileNotIn applies the NotIn predicate on the "word_file" field.
func WordFileNotIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldWordFile, vs...))
}

// WordFileGT applies the GT predicate on the "word_file" field.
func WordFileGT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldWordFile, v))
}

// WordFileGTE applies the GTE predicate on the "word_file" field.
func WordFileGTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldWordFile, v))
}

// WordFileLT applies the LT predicate on the "word_file" field.
func WordFileLT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldWordFile, v))
}

// WordFileLTE applies the LTE predicate on the "word_file" field.
func WordFileLTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldWordFile, v))
}

// WordFileContains applies the Contains predicate on the "word_file" field.
func WordFileContains(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContains(FieldWordFile, v))
}

// WordFileHasPrefix applies the HasPrefix predicate on the "word_file" field.
func WordFileHasPrefix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasPrefix(FieldWordFile, v))
}

// WordFileHasSuffix applies the HasSuffix predicate on the "word_file" field.
func WordFileHasSuffix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasSuffix(FieldWordFile, v))
}

// WordFileIsNil applies the IsNil predicate on the "word_file" field.
func WordFileIsNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIsNull(FieldWordFile))
}

// WordFileNotNil applies the NotNil predicate on the "word_file" field.
func WordFileNotNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotNull(FieldWordFile))
}

// WordFileEqualFold applies the EqualFold predicate on the "word_file" field.
func WordFileEqualFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEqualFold(FieldWordFile, v))
}

// WordFileContainsFold applies the ContainsFold predicate on the "word_file" field.
func WordFileContainsFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContainsFold(FieldWordFile, v))
}

// WordJSONIsNil applies the IsNil predicate on the "word_json" field.
func WordJSONIsNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIsNull(FieldWordJSON))
}

// WordJSONNotNil applies the NotNil predicate on the "word_json" field.
func WordJSONNotNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotNull(FieldWordJSON))
}

// WordCountEQ applies the EQ predicate on the "word_count" field.
func WordCountEQ(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldWordCount, v))
}

// WordCountNEQ applies the NEQ predicate on the "word_count" field.
func WordCountNEQ(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldWordCount, v))
}

// WordCountIn applies the In predicate on the "word_count" field.
func WordCountIn(vs ...int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldWordCount, vs...))
}

// WordCountNotIn applies the NotIn predicate on the "word_count" field.
func WordCountNotIn(vs ...int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldWordCount, vs...))
}

// WordCountGT applies the GT predicate on the "word_count" field.
func WordCountGT(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldWordCount, v))
}

// WordCountGTE applies the GTE predicate on the "word_count" field.
func WordCountGTE(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldWordCount, v))
}

// WordCountLT applies the LT predicate on the "word_count" field.
func WordCountLT(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldWordCount, v))
}

// WordCountLTE applies the LTE predicate on the "word_count" field.
func WordCountLTE(v int) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldWordCount, v))
}

// WordCountIsNil applies the IsNil predicate on the "word_count" field.
func WordCountIsNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIsNull(FieldWordCount))
}

// WordCountNotNil applies the NotNil predicate on the "word_count" field.
func WordCountNotNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotNull(FieldWordCount))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotNull(FieldCreatedBy))
}

// IsLockedEQ applies the EQ predicate on the "is_locked" field.
func IsLockedEQ(v bool) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldIsLocked, v))
}

// IsLockedNEQ applies the NEQ predicate on the "is_locked" field.
func IsLockedNEQ(v bool) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldIsLocked, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Wordlist {
	return predicate.Wordlist(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TargetsTable, TargetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.Target) predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRules applies the HasEdge predicate on the "rules" edge.
func HasRules() predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RulesTable, RulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRulesWith applies the HasEdge predicate on the "rules" edge with a given conditions (other predicates).
func HasRulesWith(preds ...predicate.Rule) predicate.Wordlist {
	return predicate.Wordlist(func(s *sql.Selector) {
		step := newRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Wordlist) predicate.Wordlist {
	return predicate.Wordlist(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Wordlist) predicate.Wordlist {
	return predicate.Wordlist(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Wordlist) predicate.Wordlist {
	return predicate.Wordlist(sql.NotPredicates(p))
}
