// Code generated by ent, DO NOT EDIT.

package defender

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the defender type in the database.
	Label = "defender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProxyPort holds the string denoting the proxy_port field in the database.
	FieldProxyPort = "proxy_port"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrinciples holds the string denoting the principles edge name in mutations.
	EdgePrinciples = "principles"
	// EdgeDecisions holds the string denoting the decisions edge name in mutations.
	EdgeDecisions = "decisions"
	// Table holds the table name of the defender in the database.
	Table = "defenders"
	// PrinciplesTable is the table that holds the principles relation/edge. The primary key declared below.
	PrinciplesTable = "defenders_principles"
	// PrinciplesInverseTable is the table name for the Principle entity.
	// It exists in this package in order to avoid circular dependency with the "principle" package.
	PrinciplesInverseTable = "principles"
	// DecisionsTable is the table that holds the decisions relation/edge. The primary key declared below.
	DecisionsTable = "defenders_decisions"
	// DecisionsInverseTable is the table name for the Decision entity.
	// It exists in this package in order to avoid circular dependency with the "decision" package.
	DecisionsInverseTable = "decisions"
)

// Columns holds all SQL columns for defender fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldProxyPort,
	FieldStatus,
	FieldDetails,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// PrinciplesPrimaryKey and PrinciplesColumn2 are the table columns denoting the
	// primary key for the principles relation (M2M).
	PrinciplesPrimaryKey = []string{"defender", "principle"}
	// DecisionsPrimaryKey and DecisionsColumn2 are the table columns denoting the
	// primary key for the decisions relation (M2M).
	DecisionsPrimaryKey = []string{"defender", "decision"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusNormal   Status = "normal"
	StatusAbnormal Status = "abnormal"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNormal, StatusAbnormal:
		return nil
	default:
		return fmt.Errorf("defender: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Defender queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProxyPort orders the results by the proxy_port field.
func ByProxyPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyPort, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrinciplesCount orders the results by principles count.
func ByPrinciplesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrinciplesStep(), opts...)
	}
}

// ByPrinciples orders the results by principles terms.
func ByPrinciples(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrinciplesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDecisionsCount orders the results by decisions count.
func ByDecisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDecisionsStep(), opts...)
	}
}

// ByDecisions orders the results by decisions terms.
func ByDecisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDecisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPrinciplesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrinciplesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PrinciplesTable, PrinciplesPrimaryKey...),
	)
}
func newDecisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DecisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DecisionsTable, DecisionsPrimaryKey...),
	)
}
